export default {
  getProductsCompareHeader: state => () => {
    return [
      {
        text: 'Item',
        align: 'center'
      },
      {
        text: 'NPC price per item',
        align: 'center'
      },
      {
        text: 'NPC price per entchanted item',
        align: 'center'
      },
      {
        text: 'NPC price per block',
        align: 'center'
      },
      {
        text: 'Bazaar price per item',
        align: 'center'
      },
      {
        text: 'Bazaar price per entchanted item',
        align: 'center'
      },
      {
        text: 'Bazaar price per block',
        align: 'center'
      },
      {
        text: 'Profit per item',
        align: 'center'
      },
      {
        text: 'Profit per entchanted item',
        align: 'center'
      },
      {
        text: 'Profit per block',
        align: 'center'
      }
    ]
  },
  getBazaarProducts: state => () => {
    return state.products
  },
  getNpcAndProfitProducts: (state, getters) => () => {
    return [
      {
        type_name: 'Farming',
        type_id: 1,
        name: 'Wheat',
        npc: {
          item_id: 'WHEAT',
          item: 2.33333,
          ec_item_id: 'ENCHANTED_BREAD',
          ec_item: 140,
          block_id: 'HAY_BLOCK',
          block: 21,
        },
        profit: {
          item: (getters.getBazaarProducts()['WHEAT'] ? getters.getBazaarProducts()['WHEAT'].quick_status.sellPrice : 0) - 2.33333,
          ec_item: (getters.getBazaarProducts()['ENCHANTED_BREAD'] ? getters.getBazaarProducts()['ENCHANTED_BREAD'].quick_status.sellPrice : 0) - 140,
          block: (getters.getBazaarProducts()['HAY_BLOCK'] ? getters.getBazaarProducts()['HAY_BLOCK'].quick_status.sellPrice : 0) - 21
        }
      },
      {
        type_name: 'Farming',
        type_id: 1,
        name: 'Carrot',
        npc: {
          item_id: 'CARROT_ITEM',
          item: 2.33333,
          ec_item_id: 'ENCHANTED_CARROT',
          ec_item: 373.33333,
          block_id: null,
          block: 0,
        },
        profit: {
          item: (getters.getBazaarProducts()['CARROT_ITEM'] ? getters.getBazaarProducts()['CARROT_ITEM'].quick_status.sellPrice : 0) - 2.33333,
          ec_item: (getters.getBazaarProducts()['ENCHANTED_CARROT'] ? getters.getBazaarProducts()['ENCHANTED_CARROT'].quick_status.sellPrice : 0) - 373.33333,
          block: 0
        }
      },
      {
        type_name: 'Farming',
        type_id: 1,
        name: 'Potato',
        npc: {
          item_id: 'POTATO_ITEM',
          item: 2.33333,
          ec_item_id: 'ENCHANTED_POTATO',
          ec_item: 373.33333,
          block_id: null,
          block: 0,
        },
        profit: {
          item: (getters.getBazaarProducts()['POTATO_ITEM'] ? getters.getBazaarProducts()['POTATO_ITEM'].quick_status.sellPrice : 0) - 2.33333,
          ec_item: (getters.getBazaarProducts()['ENCHANTED_POTATO'] ? getters.getBazaarProducts()['ENCHANTED_POTATO'].quick_status.sellPrice : 0) - 373.33333,
          block: 0
        }
      },
      {
        type_name: 'Farming',
        type_id: 1,
        name: 'Melon',
        npc: {
          item_id: 'MELON',
          item: 2,
          ec_item_id: 'ENCHANTED_MELON',
          ec_item: 320,
          block_id: null,
          block: 0,
        },
        profit: {
          item: (getters.getBazaarProducts()['MELON'] ? getters.getBazaarProducts()['MELON'].quick_status.sellPrice : 0) - 2,
          ec_item: (getters.getBazaarProducts()['ENCHANTED_MELON'] ? getters.getBazaarProducts()['ENCHANTED_MELON'].quick_status.sellPrice : 0) - 320,
          block: 0
        }
      },
      {
        type_name: 'Farming',
        type_id: 1,
        name: 'Sugar Cane',
        npc: {
          item_id: 'SUGAR_CANE',
          item: 5,
          ec_item_id: 'ENCHANTED_SUGAR',
          ec_item: 800,
          block_id: 'ENCHANTED_PAPER',
          block: 960,
        },
        profit: {
          item: (getters.getBazaarProducts()['SUGAR_CANE'] ? getters.getBazaarProducts()['SUGAR_CANE'].quick_status.sellPrice : 0) - 5,
          ec_item: (getters.getBazaarProducts()['ENCHANTED_SUGAR'] ? getters.getBazaarProducts()['ENCHANTED_SUGAR'].quick_status.sellPrice : 0) - 800,
          block: (getters.getBazaarProducts()['ENCHANTED_PAPER'] ? getters.getBazaarProducts()['ENCHANTED_PAPER'].quick_status.sellPrice : 0) - 960
        }
      },
      {
        type_name: 'Farming',
        type_id: 1,
        name: 'Pumpkin',
        npc: {
          item_id: 'PUMPKIN',
          item: 8,
          ec_item_id: 'ENCHANTED_PUMPKIN',
          ec_item: 1280,
          block_id: null,
          block: 0,
        },
        profit: {
          item: (getters.getBazaarProducts()['PUMPKIN'] ? getters.getBazaarProducts()['PUMPKIN'].quick_status.sellPrice : 0) - 8,
          ec_item: (getters.getBazaarProducts()['ENCHANTED_PUMPKIN'] ? getters.getBazaarProducts()['ENCHANTED_PUMPKIN'].quick_status.sellPrice : 0) - 1280,
          block: 0
        }
      },
      {
        type_name: 'Farming',
        type_id: 1,
        name: 'Cocoa Beans',
        npc: {
          item_id: 'INK_SACK:3',
          item: 5,
          ec_item_id: 'ENCHANTED_COCOA',
          ec_item: 800,
          block_id: null,
          block: 0,
        },
        profit: {
          item: (getters.getBazaarProducts()['INK_SACK:3'] ? getters.getBazaarProducts()['INK_SACK:3'].quick_status.sellPrice : 0) - 5,
          ec_item: (getters.getBazaarProducts()['ENCHANTED_COCOA'] ? getters.getBazaarProducts()['ENCHANTED_COCOA'].quick_status.sellPrice : 0) - 800,
          block: 0
        }
      },
      {
        type_name: 'Farming',
        type_id: 1,
        name: 'Red Mushrooms',
        npc: {
          item_id: 'RED_MUSHROOM',
          item: 12,
          ec_item_id: 'ENCHANTED_RED_MUSHROOM',
          ec_item: 1920,
          block_id: 'HUGE_MUSHROOM_2',
          block: 108,
        },
        profit: {
          item: (getters.getBazaarProducts()['RED_MUSHROOM'] ? getters.getBazaarProducts()['RED_MUSHROOM'].quick_status.sellPrice : 0) - 12,
          ec_item: (getters.getBazaarProducts()['ENCHANTED_RED_MUSHROOM'] ? getters.getBazaarProducts()['ENCHANTED_RED_MUSHROOM'].quick_status.sellPrice : 0) - 1920,
          block: (getters.getBazaarProducts()['HUGE_MUSHROOM_2'] ? getters.getBazaarProducts()['HUGE_MUSHROOM_2'].quick_status.sellPrice : 0) - 108
        }
      },
      {
        type_name: 'Farming',
        type_id: 1,
        name: 'Brown Mushrooms',
        npc: {
          item_id: 'BROWN_MUSHROOM',
          item: 12,
          ec_item_id: 'ENCHANTED_BROWN_MUSHROOM',
          ec_item: 1920,
          block_id: 'HUGE_MUSHROOM_1',
          block: 108,
        },
        profit: {
          item: (getters.getBazaarProducts()['BROWN_MUSHROOM'] ? getters.getBazaarProducts()['BROWN_MUSHROOM'].quick_status.sellPrice : 0) - 12,
          ec_item: (getters.getBazaarProducts()['ENCHANTED_BROWN_MUSHROOM'] ? getters.getBazaarProducts()['ENCHANTED_BROWN_MUSHROOM'].quick_status.sellPrice : 0) - 1920,
          block: (getters.getBazaarProducts()['HUGE_MUSHROOM_1'] ? getters.getBazaarProducts()['HUGE_MUSHROOM_1'].quick_status.sellPrice : 0) - 108
        }
      },
      {
        type_name: 'Farming',
        type_id: 1,
        name: 'Nether Wart',
        npc: {
          item_id: 'NETHER_STALK',
          item: 10,
          ec_item_id: 'ENCHANTED_NETHER_STALK',
          ec_item: 1600,
          block_id: null,
          block: 0,
        },
        profit: {
          item: (getters.getBazaarProducts()['NETHER_STALK'] ? getters.getBazaarProducts()['NETHER_STALK'].quick_status.sellPrice : 0) - 10,
          ec_item: (getters.getBazaarProducts()['ENCHANTED_NETHER_STALK'] ? getters.getBazaarProducts()['ENCHANTED_NETHER_STALK'].quick_status.sellPrice : 0) - 1600,
          block: 0
        }
      },
      {
        type_name: 'Farming',
        type_id: 1,
        name: 'Rabbit\'s Foot',
        npc: {
          item_id: 'RABBIT_FOOT',
          item: 10,
          ec_item_id: 'ENCHANTED_RABBIT',
          ec_item: 1600,
          block_id: null,
          block: 0,
        },
        profit: {
          item: (getters.getBazaarProducts()['RABBIT_FOOT'] ? getters.getBazaarProducts()['RABBIT_FOOT'].quick_status.sellPrice : 0) - 10,
          ec_item: (getters.getBazaarProducts()['ENCHANTED_RABBIT'] ? getters.getBazaarProducts()['ENCHANTED_RABBIT'].quick_status.sellPrice : 0) - 1600,
          block: 0
        }
      },
      {
        type_name: 'Mining',
        type_id: 2,
        name: 'Coal',
        npc: {
          item_id: 'COAL',
          item: 4,
          ec_item_id: 'ENCHANTED_RABBIT',
          ec_item: 640,
          block_id: 'COAL_BLOCK',
          block: 0,
        },
        profit: {
          item: (getters.getBazaarProducts()['COAL'] ? getters.getBazaarProducts()['COAL'].quick_status.sellPrice : 0) - 4,
          ec_item: (getters.getBazaarProducts()['ENCHANTED_RABBIT'] ? getters.getBazaarProducts()['ENCHANTED_RABBIT'].quick_status.sellPrice : 0) - 640,
          block: (getters.getBazaarProducts()['COAL_BLOCK'] ? getters.getBazaarProducts()['COAL_BLOCK'].quick_status.sellPrice : 0) - 0
        }
      },
      {
        type_name: 'Mining',
        type_id: 2,
        name: 'Iron Ingot (Mine Merchant)',
        npc: {
          item_id: 'IRON_INGOT',
          item: 5.5,
          ec_item_id: 'ENCHANTED_IRON',
          ec_item: 880,
          block_id: 'IRON_BLOCK',
          block: 0,
        },
        profit: {
          item: (getters.getBazaarProducts()['IRON_INGOT'] ? getters.getBazaarProducts()['IRON_INGOT'].quick_status.sellPrice : 0) - 5.5,
          ec_item: (getters.getBazaarProducts()['ENCHANTED_IRON'] ? getters.getBazaarProducts()['ENCHANTED_IRON'].quick_status.sellPrice : 0) - 880,
          block: (getters.getBazaarProducts()['IRON_BLOCK'] ? getters.getBazaarProducts()['IRON_BLOCK'].quick_status.sellPrice : 0) - 0
        }
      },
      {
        type_name: 'Mining',
        type_id: 2,
        name: 'Iron Ingot (Iron Forger)',
        npc: {
          item_id: 'IRON_INGOT',
          item: 5,
          ec_item_id: 'ENCHANTED_IRON',
          ec_item: 800,
          block_id: 'IRON_BLOCK',
          block: 0,
        },
        profit: {
          item: (getters.getBazaarProducts()['IRON_INGOT'] ? getters.getBazaarProducts()['IRON_INGOT'].quick_status.sellPrice : 0) - 5,
          ec_item: (getters.getBazaarProducts()['ENCHANTED_IRON'] ? getters.getBazaarProducts()['ENCHANTED_IRON'].quick_status.sellPrice : 0) - 800,
          block: (getters.getBazaarProducts()['IRON_BLOCK'] ? getters.getBazaarProducts()['IRON_BLOCK'].quick_status.sellPrice : 0) - 0
        }
      },
      {
        type_name: 'Mining',
        type_id: 2,
        name: 'Gold Ingot (Mine Merchant)',
        npc: {
          item_id: 'GOLD_INGOT',
          item: 6,
          ec_item_id: 'ENCHANTED_GOLD',
          ec_item: 960,
          block_id: 'GOLD_BLOCK',
          block: 0,
        },
        profit: {
          item: (getters.getBazaarProducts()['GOLD_INGOT'] ? getters.getBazaarProducts()['GOLD_INGOT'].quick_status.sellPrice : 0) - 6,
          ec_item: (getters.getBazaarProducts()['ENCHANTED_GOLD'] ? getters.getBazaarProducts()['ENCHANTED_GOLD'].quick_status.sellPrice : 0) - 960,
          block: (getters.getBazaarProducts()['GOLD_BLOCK'] ? getters.getBazaarProducts()['GOLD_BLOCK'].quick_status.sellPrice : 0) - 0
        }
      },
      {
        type_name: 'Mining',
        type_id: 2,
        name: 'Gold Ingot (Gold Forger)',
        npc: {
          item_id: 'GOLD_INGOT',
          item: 5.5,
          ec_item_id: 'ENCHANTED_GOLD',
          ec_item: 880,
          block_id: 'GOLD_BLOCK',
          block: 0,
        },
        profit: {
          item: (getters.getBazaarProducts()['GOLD_INGOT'] ? getters.getBazaarProducts()['GOLD_INGOT'].quick_status.sellPrice : 0) - 5.5,
          ec_item: (getters.getBazaarProducts()['ENCHANTED_GOLD'] ? getters.getBazaarProducts()['ENCHANTED_GOLD'].quick_status.sellPrice : 0) - 880,
          block: (getters.getBazaarProducts()['GOLD_BLOCK'] ? getters.getBazaarProducts()['GOLD_BLOCK'].quick_status.sellPrice : 0) - 0
        }
      },
      {
        type_name: 'Mining',
        type_id: 2,
        name: 'Gravel (Mine Merchant)',
        npc: {
          item_id: 'GRAVEL',
          item: 6,
          ec_item_id: null,
          ec_item: 0,
          block_id: null,
          block: 0,
        },
        profit: {
          item: (getters.getBazaarProducts()['GRAVEL'] ? getters.getBazaarProducts()['GRAVEL'].quick_status.sellPrice : 0) - 6,
          ec_item: 0,
          block: 0
        }
      },
      {
        type_name: 'Mining',
        type_id: 2,
        name: 'Gravel (Pat)',
        npc: {
          item_id: 'GRAVEL',
          item: 4.33333,
          ec_item_id: null,
          ec_item: 0,
          block_id: null,
          block: 0,
        },
        profit: {
          item: (getters.getBazaarProducts()['GRAVEL'] ? getters.getBazaarProducts()['GRAVEL'].quick_status.sellPrice : 0) - 4.33333,
          ec_item: 0,
          block: 0
        }
      },
      {
        type_name: 'Mining',
        type_id: 2,
        name: 'Cobblestone',
        npc: {
          item_id: 'COBBLESTONE',
          item: 3,
          ec_item_id: 'ENCHANTED_COBBLESTONE',
          ec_item: 480,
          block_id: null,
          block: 0,
        },
        profit: {
          item: (getters.getBazaarProducts()['COBBLESTONE'] ? getters.getBazaarProducts()['COBBLESTONE'].quick_status.sellPrice : 0) - 3,
          ec_item: (getters.getBazaarProducts()['ENCHANTED_COBBLESTONE'] ? getters.getBazaarProducts()['ENCHANTED_COBBLESTONE'].quick_status.sellPrice : 0) - 480,
          block: 0
        }
      },
      {
        type_name: 'Mining',
        type_id: 2,
        name: 'Sand',
        npc: {
          item_id: 'SAND',
          item: 4,
          ec_item_id: 'ENCHANTED_SAND',
          ec_item: 640,
          block_id: null,
          block: 0,
        },
        profit: {
          item: (getters.getBazaarProducts()['SAND'] ? getters.getBazaarProducts()['SAND'].quick_status.sellPrice : 0) - 4,
          ec_item: (getters.getBazaarProducts()['ENCHANTED_SAND'] ? getters.getBazaarProducts()['ENCHANTED_SAND'].quick_status.sellPrice : 0) - 640,
          block: 0
        }
      },
      {
        type_name: 'Mining',
        type_id: 2,
        name: 'Ice (Builder)',
        npc: {
          item_id: 'ICE',
          item: 1,
          ec_item_id: 'ENCHANTED_ICE',
          ec_item: 160,
          block_id: 'PACKED_ICE',
          block: 9,
        },
        profit: {
          item: (getters.getBazaarProducts()['ICE'] ? getters.getBazaarProducts()['ICE'].quick_status.sellPrice : 0) - 1,
          ec_item: (getters.getBazaarProducts()['ENCHANTED_ICE'] ? getters.getBazaarProducts()['ENCHANTED_ICE'].quick_status.sellPrice : 0) - 160,
          block: (getters.getBazaarProducts()['PACKED_ICE'] ? getters.getBazaarProducts()['PACKED_ICE'].quick_status.sellPrice : 0) - 9
        }
      },
      {
        type_name: 'Mining',
        type_id: 2,
        name: 'Ice (Sherry)',
        npc: {
          item_id: 'ICE',
          item: 1,
          ec_item_id: 'ENCHANTED_ICE',
          ec_item: 160,
          block_id: 'PACKED_ICE',
          block: 9,
        },
        profit: {
          item: (getters.getBazaarProducts()['ICE'] ? getters.getBazaarProducts()['ICE'].quick_status.sellPrice : 0) - 1,
          ec_item: (getters.getBazaarProducts()['ENCHANTED_ICE'] ? getters.getBazaarProducts()['ENCHANTED_ICE'].quick_status.sellPrice : 0) - 160,
          block: (getters.getBazaarProducts()['PACKED_ICE'] ? getters.getBazaarProducts()['PACKED_ICE'].quick_status.sellPrice : 0) - 9
        }
      },
      {
        type_name: 'Mining',
        type_id: 2,
        name: 'Packed Ice (Builder)',
        npc: {
          item_id: 'PACKED_ICE',
          item: 9,
          ec_item_id: 'ENCHANTED_PACKED_ICE',
          ec_item: 160,
          block_id: null,
          block: 0,
        },
        profit: {
          item: (getters.getBazaarProducts()['PACKED_ICE'] ? getters.getBazaarProducts()['PACKED_ICE'].quick_status.sellPrice : 0) - 9,
          ec_item: (getters.getBazaarProducts()['ENCHANTED_PACKED_ICE'] ? getters.getBazaarProducts()['ENCHANTED_PACKED_ICE'].quick_status.sellPrice : 0) - 160,
          block: 0
        }
      },
      {
        type_name: 'Mining',
        type_id: 2,
        name: 'Packed Ice (Sherry)',
        npc: {
          item_id: 'PACKED_ICE',
          item: 9,
          ec_item_id: 'ENCHANTED_PACKED_ICE',
          ec_item: 160,
          block_id: null,
          block: 0,
        },
        profit: {
          item: (getters.getBazaarProducts()['PACKED_ICE'] ? getters.getBazaarProducts()['PACKED_ICE'].quick_status.sellPrice : 0) - 9,
          ec_item: (getters.getBazaarProducts()['ENCHANTED_PACKED_ICE'] ? getters.getBazaarProducts()['ENCHANTED_PACKED_ICE'].quick_status.sellPrice : 0) - 160,
          block: 0
        }
      },
      {
        type_name: 'Mining',
        type_id: 2,
        name: 'Block of Quartz',
        npc: {
          item_id: 'QUARTZ_BLOCK',
          item: 32,
          ec_item_id: 'ENCHANTED_QUARTZ_BLOCK',
          ec_item: 1280,
          block_id: null,
          block: 0,
        },
        profit: {
          item: (getters.getBazaarProducts()['QUARTZ_BLOCK'] ? getters.getBazaarProducts()['QUARTZ_BLOCK'].quick_status.sellPrice : 0) - 32,
          ec_item: (getters.getBazaarProducts()['ENCHANTED_QUARTZ_BLOCK'] ? getters.getBazaarProducts()['ENCHANTED_QUARTZ_BLOCK'].quick_status.sellPrice : 0) - 1280,
          block: 0
        }
      },
      {
        type_name: 'Mining',
        type_id: 2,
        name: 'Flint',
        npc: {
          item_id: 'FLINT',
          item: 6,
          ec_item_id: 'ENCHANTED_FLINT',
          ec_item: 960,
          block_id: null,
          block: 0,
        },
        profit: {
          item: (getters.getBazaarProducts()['FLINT'] ? getters.getBazaarProducts()['FLINT'].quick_status.sellPrice : 0) - 6,
          ec_item: (getters.getBazaarProducts()['ENCHANTED_FLINT'] ? getters.getBazaarProducts()['ENCHANTED_FLINT'].quick_status.sellPrice : 0) - 960,
          block: 0
        }
      },
      {
        type_name: 'Mining',
        type_id: 2,
        name: 'End Stone',
        npc: {
          item_id: 'ENDER_STONE',
          item: 10,
          ec_item_id: 'ENCHANTED_ENDSTONE',
          ec_item: 1600,
          block_id: null,
          block: 0,
        },
        profit: {
          item: (getters.getBazaarProducts()['ENDER_STONE'] ? getters.getBazaarProducts()['ENDER_STONE'].quick_status.sellPrice : 0) - 10,
          ec_item: (getters.getBazaarProducts()['ENCHANTED_ENDSTONE'] ? getters.getBazaarProducts()['ENCHANTED_ENDSTONE'].quick_status.sellPrice : 0) - 1600,
          block: 0
        }
      },
      {
        type_name: 'Mining',
        type_id: 2,
        name: 'Obsidian',
        npc: {
          item_id: 'OBSIDIAN',
          item: 50,
          ec_item_id: 'ENCHANTED_OBSIDIAN',
          ec_item: 8000,
          block_id: null,
          block: 0,
        },
        profit: {
          item: (getters.getBazaarProducts()['OBSIDIAN'] ? getters.getBazaarProducts()['OBSIDIAN'].quick_status.sellPrice : 0) - 50,
          ec_item: (getters.getBazaarProducts()['ENCHANTED_OBSIDIAN'] ? getters.getBazaarProducts()['ENCHANTED_OBSIDIAN'].quick_status.sellPrice : 0) - 8000,
          block: 0
        }
      },
      {
        type_name: 'Combat',
        type_id: 3,
        name: 'Rotten Flesh',
        npc: {
          item_id: 'ROTTEN_FLESH',
          item: 8,
          ec_item_id: 'ENCHANTED_ROTTEN_FLESH',
          ec_item: 1280,
          block_id: null,
          block: 0,
        },
        profit: {
          item: (getters.getBazaarProducts()['ROTTEN_FLESH'] ? getters.getBazaarProducts()['ROTTEN_FLESH'].quick_status.sellPrice : 0) - 8,
          ec_item: (getters.getBazaarProducts()['ENCHANTED_ROTTEN_FLESH'] ? getters.getBazaarProducts()['ENCHANTED_ROTTEN_FLESH'].quick_status.sellPrice : 0) - 1280,
          block: 0
        }
      },
      {
        type_name: 'Combat',
        type_id: 3,
        name: 'Bone',
        npc: {
          item_id: 'ROTTEN_FLESH',
          item: 8,
          ec_item_id: 'ENCHANTED_ROTTEN_FLESH',
          ec_item: 1280,
          block_id: null,
          block: 0,
        },
        profit: {
          item: (getters.getBazaarProducts()['ROTTEN_FLESH'] ? getters.getBazaarProducts()['ROTTEN_FLESH'].quick_status.sellPrice : 0) - 8,
          ec_item: (getters.getBazaarProducts()['ENCHANTED_ROTTEN_FLESH'] ? getters.getBazaarProducts()['ENCHANTED_ROTTEN_FLESH'].quick_status.sellPrice : 0) - 1280,
          block: 0
        }
      },
      {
        type_name: 'Combat',
        type_id: 3,
        name: 'String',
        npc: {
          item_id: 'STRING',
          item: 10,
          ec_item_id: 'ENCHANTED_STRING',
          ec_item: 1920,
          block_id: null,
          block: 0,
        },
        profit: {
          item: (getters.getBazaarProducts()['STRING'] ? getters.getBazaarProducts()['STRING'].quick_status.sellPrice : 0) - 10,
          ec_item: (getters.getBazaarProducts()['ENCHANTED_STRING'] ? getters.getBazaarProducts()['ENCHANTED_STRING'].quick_status.sellPrice : 0) - 1920,
          block: 0
        }
      },
      {
        type_name: 'Combat',
        type_id: 3,
        name: 'Slimeball',
        npc: {
          item_id: 'SLIME_BALL',
          item: 14,
          ec_item_id: 'ENCHANTED_SLIME_BALL	',
          ec_item: 2240,
          block_id: null,
          block: 0,
        },
        profit: {
          item: (getters.getBazaarProducts()['SLIME_BALL'] ? getters.getBazaarProducts()['SLIME_BALL'].quick_status.sellPrice : 0) - 14,
          ec_item: (getters.getBazaarProducts()['ENCHANTED_SLIME_BALL	'] ? getters.getBazaarProducts()['ENCHANTED_SLIME_BALL	'].quick_status.sellPrice : 0) - 2240,
          block: 0
        }
      },
      {
        type_name: 'Combat',
        type_id: 3,
        name: 'Gunpowder',
        npc: {
          item_id: 'SULPHUR',
          item: 10,
          ec_item_id: 'ENCHANTED_GUNPOWDER',
          ec_item: 1600,
          block_id: null,
          block: 0,
        },
        profit: {
          item: (getters.getBazaarProducts()['SULPHUR'] ? getters.getBazaarProducts()['SULPHUR'].quick_status.sellPrice : 0) - 10,
          ec_item: (getters.getBazaarProducts()['ENCHANTED_GUNPOWDER'] ? getters.getBazaarProducts()['ENCHANTED_GUNPOWDER'].quick_status.sellPrice : 0) - 1600,
          block: 0
        }
      },
      {
        type_name: 'Combat',
        type_id: 3,
        name: 'Spider Eye',
        npc: {
          item_id: 'SPIDER_EYE',
          item: 12,
          ec_item_id: 'ENCHANTED_SPIDER_EYE',
          ec_item: 1920,
          block_id: null,
          block: 0,
        },
        profit: {
          item: (getters.getBazaarProducts()['SPIDER_EYE'] ? getters.getBazaarProducts()['SPIDER_EYE'].quick_status.sellPrice : 0) - 12,
          ec_item: (getters.getBazaarProducts()['ENCHANTED_SPIDER_EYE'] ? getters.getBazaarProducts()['ENCHANTED_SPIDER_EYE'].quick_status.sellPrice : 0) - 1920,
          block: 0
        }
      },
      {
        type_name: 'Combat',
        type_id: 3,
        name: 'Ghast Tear',
        npc: {
          item_id: 'GHAST_TEAR',
          item: 200,
          ec_item_id: 'ENCHANTED_GHAST_TEAR',
          ec_item: 1000,
          block_id: null,
          block: 0,
        },
        profit: {
          item: (getters.getBazaarProducts()['GHAST_TEAR'] ? getters.getBazaarProducts()['GHAST_TEAR'].quick_status.sellPrice : 0) - 200,
          ec_item: (getters.getBazaarProducts()['ENCHANTED_GHAST_TEAR'] ? getters.getBazaarProducts()['ENCHANTED_GHAST_TEAR'].quick_status.sellPrice : 0) - 1000,
          block: 0
        }
      },
      {
        type_name: 'Combat',
        type_id: 3,
        name: 'Magma Crean',
        npc: {
          item_id: 'MAGMA_CREAM',
          item: 20,
          ec_item_id: 'ENCHANTED_MAGMA_CREAM',
          ec_item: 3200,
          block_id: null,
          block: 0,
        },
        profit: {
          item: (getters.getBazaarProducts()['MAGMA_CREAM'] ? getters.getBazaarProducts()['MAGMA_CREAM'].quick_status.sellPrice : 0) - 20,
          ec_item: (getters.getBazaarProducts()['ENCHANTED_MAGMA_CREAM'] ? getters.getBazaarProducts()['ENCHANTED_MAGMA_CREAM'].quick_status.sellPrice : 0) - 3200,
          block: 0
        }
      },
      {
        type_name: 'Foraging',
        type_id: 4,
        name: 'Oak Wood',
        npc: {
          item_id: 'LOG:0',
          item: 5,
          ec_item_id: 'ENCHANTED_OAK_LOG',
          ec_item: 800,
          block_id: null,
          block: 0,
        },
        profit: {
          item: (getters.getBazaarProducts()['LOG:0'] ? getters.getBazaarProducts()['LOG:0'].quick_status.sellPrice : 0) - 5,
          ec_item: (getters.getBazaarProducts()['ENCHANTED_OAK_LOG'] ? getters.getBazaarProducts()['ENCHANTED_OAK_LOG'].quick_status.sellPrice : 0) - 800,
          block: 0
        }
      },
      {
        type_name: 'Foraging',
        type_id: 4,
        name: 'Birch Wood',
        npc: {
          item_id: 'LOG:2',
          item: 5,
          ec_item_id: 'ENCHANTED_BIRCH_LOG',
          ec_item: 800,
          block_id: null,
          block: 0,
        },
        profit: {
          item: (getters.getBazaarProducts()['LOG:2'] ? getters.getBazaarProducts()['LOG:2'].quick_status.sellPrice : 0) - 5,
          ec_item: (getters.getBazaarProducts()['ENCHANTED_BIRCH_LOG'] ? getters.getBazaarProducts()['ENCHANTED_BIRCH_LOG'].quick_status.sellPrice : 0) - 800,
          block: 0
        }
      },
      {
        type_name: 'Foraging',
        type_id: 4,
        name: 'Dark Oak Wood',
        npc: {
          item_id: 'LOG_2:1',
          item: 5,
          ec_item_id: 'ENCHANTED_DARK_OAK_LOG',
          ec_item: 800,
          block_id: null,
          block: 0,
        },
        profit: {
          item: (getters.getBazaarProducts()['LOG_2:1'] ? getters.getBazaarProducts()['LOG_2:1'].quick_status.sellPrice : 0) - 5,
          ec_item: (getters.getBazaarProducts()['ENCHANTED_DARK_OAK_LOG'] ? getters.getBazaarProducts()['ENCHANTED_DARK_OAK_LOG'].quick_status.sellPrice : 0) - 800,
          block: 0
        }
      },
      {
        type_name: 'Foraging',
        type_id: 4,
        name: 'Spruce Wood',
        npc: {
          item_id: 'LOG:1',
          item: 5,
          ec_item_id: 'ENCHANTED_SPRUCE_LOG',
          ec_item: 800,
          block_id: null,
          block: 0,
        },
        profit: {
          item: (getters.getBazaarProducts()['LOG:1'] ? getters.getBazaarProducts()['LOG:1'].quick_status.sellPrice : 0) - 5,
          ec_item: (getters.getBazaarProducts()['ENCHANTED_SPRUCE_LOG'] ? getters.getBazaarProducts()['ENCHANTED_SPRUCE_LOG'].quick_status.sellPrice : 0) - 800,
          block: 0
        }
      },
      {
        type_name: 'Foraging',
        type_id: 4,
        name: 'Acacia Wood',
        npc: {
          item_id: 'LOG_2:0',
          item: 5,
          ec_item_id: 'ENCHANTED_ACACIA_LOG',
          ec_item: 800,
          block_id: null,
          block: 0,
        },
        profit: {
          item: (getters.getBazaarProducts()['LOG_2:0'] ? getters.getBazaarProducts()['LOG_2:0'].quick_status.sellPrice : 0) - 5,
          ec_item: (getters.getBazaarProducts()['ENCHANTED_ACACIA_LOG'] ? getters.getBazaarProducts()['ENCHANTED_ACACIA_LOG'].quick_status.sellPrice : 0) - 800,
          block: 0
        }
      },
      {
        type_name: 'Foraging',
        type_id: 4,
        name: 'Jungle Wood',
        npc: {
          item_id: 'LOG:3',
          item: 5,
          ec_item_id: 'ENCHANTED_JUNGLE_LOG',
          ec_item: 800,
          block_id: null,
          block: 0,
        },
        profit: {
          item: (getters.getBazaarProducts()['LOG:3'] ? getters.getBazaarProducts()['LOG:3'].quick_status.sellPrice : 0) - 5,
          ec_item: (getters.getBazaarProducts()['ENCHANTED_JUNGLE_LOG'] ? getters.getBazaarProducts()['ENCHANTED_JUNGLE_LOG'].quick_status.sellPrice : 0) - 800,
          block: 0
        }
      },
      {
        type_name: 'Fishing',
        type_id: 5,
        name: 'Raw Fish',
        npc: {
          item_id: 'RAW_FISH',
          item: 20,
          ec_item_id: 'ENCHANTED_RAW_FISH',
          ec_item: 3200,
          block_id: null,
          block: 0,
        },
        profit: {
          item: (getters.getBazaarProducts()['RAW_FISH'] ? getters.getBazaarProducts()['RAW_FISH'].quick_status.sellPrice : 0) - 20,
          ec_item: (getters.getBazaarProducts()['ENCHANTED_RAW_FISH'] ? getters.getBazaarProducts()['ENCHANTED_RAW_FISH'].quick_status.sellPrice : 0) - 3200,
          block: 0
        }
      },
      {
        type_name: 'Fishing',
        type_id: 5,
        name: 'Raw Fish',
        npc: {
          item_id: 'RAW_FISH',
          item: 20,
          ec_item_id: 'ENCHANTED_RAW_FISH',
          ec_item: 3200,
          block_id: null,
          block: 0,
        },
        profit: {
          item: (getters.getBazaarProducts()['RAW_FISH'] ? getters.getBazaarProducts()['RAW_FISH'].quick_status.sellPrice : 0) - 20,
          ec_item: (getters.getBazaarProducts()['ENCHANTED_RAW_FISH'] ? getters.getBazaarProducts()['ENCHANTED_RAW_FISH'].quick_status.sellPrice : 0) - 3200,
          block: 0
        }
      },
      {
        type_name: 'Fishing',
        type_id: 5,
        name: 'Raw Fish',
        npc: {
          item_id: 'RAW_FISH:1',
          item: 30,
          ec_item_id: 'ENCHANTED_RAW_SALMON',
          ec_item: 4800,
          block_id: null,
          block: 0,
        },
        profit: {
          item: (getters.getBazaarProducts()['RAW_FISH:1'] ? getters.getBazaarProducts()['RAW_FISH:1'].quick_status.sellPrice : 0) - 30,
          ec_item: (getters.getBazaarProducts()['ENCHANTED_RAW_SALMON'] ? getters.getBazaarProducts()['ENCHANTED_RAW_SALMON'].quick_status.sellPrice : 0) - 4800,
          block: 0
        }
      },
      {
        type_name: 'Fishing',
        type_id: 5,
        name: 'Raw Salmon',
        npc: {
          item_id: 'RAW_FISH:1',
          item: 30,
          ec_item_id: 'ENCHANTED_RAW_SALMON',
          ec_item: 4800,
          block_id: null,
          block: 0,
        },
        profit: {
          item: (getters.getBazaarProducts()['RAW_FISH:1'] ? getters.getBazaarProducts()['RAW_FISH:1'].quick_status.sellPrice : 0) - 30,
          ec_item: (getters.getBazaarProducts()['ENCHANTED_RAW_SALMON'] ? getters.getBazaarProducts()['ENCHANTED_RAW_SALMON'].quick_status.sellPrice : 0) - 4800,
          block: 0
        }
      },
      {
        type_name: 'Fishing',
        type_id: 5,
        name: 'Clownfish',
        npc: {
          item_id: 'RAW_FISH:2',
          item: 100,
          ec_item_id: null,
          ec_item: 0,
          block_id: null,
          block: 0,
        },
        profit: {
          item: (getters.getBazaarProducts()['RAW_FISH:2'] ? getters.getBazaarProducts()['RAW_FISH:2'].quick_status.sellPrice : 0) - 100,
          ec_item: 0,
          block: 0
        }
      },
      {
        type_name: 'Fishing',
        type_id: 5,
        name: 'Pufferfish',
        npc: {
          item_id: 'RAW_FISH:3',
          item: 40,
          ec_item_id: 'ENCHANTED_PUFFERFISH',
          ec_item: 6400,
          block_id: null,
          block: 0,
        },
        profit: {
          item: (getters.getBazaarProducts()['RAW_FISH:3'] ? getters.getBazaarProducts()['RAW_FISH:3'].quick_status.sellPrice : 0) - 40,
          ec_item: (getters.getBazaarProducts()['ENCHANTED_PUFFERFISH'] ? getters.getBazaarProducts()['ENCHANTED_PUFFERFISH'].quick_status.sellPrice : 0) - 6400,
          block: 0
        }
      },
    ]
  },
  getItemsNames: state => () => {
    return {
      'AATROX_BATPHONE': 'Maddox Batphone',
      'ACACIA_FENCE': 'Acacia Fence',
      'ACACIA_DOOR_ITEM': 'Acacia Door',
      'ACACIA_FENCE_GATE': 'Acacia Fence Gate',
      'ACTIVATOR_RAIL': 'Activator Rail',
      'ACACIA_STAIRS': 'Acacia Wood Stairs',
      'ANGLER_HELMET': 'Angler Helmet',
      'ANGLER_LEGGINGS': 'Angler Leggings',
      'ANGLER_BOOTS': 'Angler Boots',
      'ANGLER_CHESTPLATE': 'Angler Chestplate',
      'ANVIL:2': 'Very Damaged Anvil',
      'ARMOR_SHOWCASE': 'Armor Stand',
      'ASPECT_OF_THE_END': 'Aspect of the End',
      'BARRIER': 'Barrier',
      'BAT_PERSON_CHESTPLATE': 'Bat Person Chestplate',
      'BAT_THE_FISH': 'Bat the Fish',
      'BEACON': 'Beacon Block',
      'BIRCH_DOOR_ITEM': 'Birch Door',
      'BITTER_ICE_TEA': 'Bitter Ice Tea',
      'BLAZE_HELMET': 'Blaze Helmet',
      'BLOBFISH_HAT': 'Blobfish Hat',
      'BOOKCASE': 'Bookcase',
      'BOW': 'Bow',
      'BREWING_STAND_ITEM': 'Brewing Stand',
      'BROWN_MUSHROOM': 'Brown Mushroom',
      'CACTUS_CHESTPLATE': 'Cactus Chestplate',
      'CANDLE_ARCH': 'Candle Arch',
      'CARPENTRY_BENCH': 'Carpentry Table',
      'CARPET:14': 'Red Carpet',
      'CARPET:7': 'Gray Carpet',
      'CARROT_STICK': 'Carrot on a Stick',
      'CHAINMAIL_HELMET': 'Chainmail Helmet',
      'CHEAP_TUXEDO_BOOTS': 'Cheap Tuxedo Oxfords',
      'CHEST_SHELVES': 'Chest Storage',
      'CLEAVER': 'Cleaver',
      'COAL_ORE': 'Coal Ore',
      'COMPACTOR': 'Compactor',
      'COOKED_FISH:1': 'Cooked Salmon',
      'CREEPER_HAT': 'Creeper Hat',
      'CRYSTAL_CHESTPLATE': 'Crystal Chestplate',
      'DANGER_2_PORTAL': 'Portal to Blazing Fortress',
      'DARK_OAK_FENCE_GATE': 'Dark Oak Fence Gate',
      'DECENT_BOW': 'Decent Bow',
      'DESK': 'Desk',
      'DIAMOND_BLOCK': 'Block of Diamond',
      'DIAMOND_HOE': 'Diamond Hoe',
      'DIAMOND_SPREADING': 'Diamond Spreading',
      'DIODE': 'Repeater',
      'DISPENSER': 'Dispenser',
      'DIVER_LEGGINGS': 'Diver\'s Trunks',
      'DOUBLE_PLANT:5': 'Peony',
      'EGG': 'Egg',
      'EMBER_CHESTPLATE': 'Ember Chestplate',
      'EMERALD': 'Emerald',
      'EMERALD_BLADE': 'Emerald Blade',
      'ENCHANTED_ACACIA_LOG': 'Enchanted Acacia Wood',
      'ENCHANTED_BONE': 'Enchanted Bone',
      'ENCHANTED_BROWN_MUSHROOM': 'Enchanted Brown Mushroom',
      'ENCHANTED_CARROT_STICK': 'Enchanted Carrot on a Stick',
      'ENCHANTED_COAL_BLOCK': 'Enchanted Block of Coal',
      'ENCHANTED_COOKED_SALMON': 'Enchanted Cooked Salmon',
      'ENCHANTED_DIAMOND_BLOCK': 'Enchanted Diamond Block',
      'ENCHANTED_ENDSTONE': 'Enchanted End Stone',
      'ENCHANTED_FLINT': 'Enchanted Flint',
      'ENCHANTED_GOLD': 'Enchanted Gold',
      'ENCHANTED_HAY_BLOCK': 'Enchanted Hay Bale',
      'ENCHANTED_INK_SACK': 'Enchanted Ink Sack',
      'ENCHANTED_LAPIS_LAZULI': 'Enchanted Lapis Lazuli',
      'ENCHANTED_MELON': 'Enchanted Melon',
      'ENCHANTED_OBSIDIAN': 'Enchanted Obsidian',
      'ENCHANTED_PORK': 'Enchanted Pork',
      'ENCHANTED_PUMPKIN': 'Enchanted Pumpkin',
      'ENCHANTED_RABBIT_HIDE': 'Enchanted Rabbit Hide',
      'ENCHANTED_REDSTONE': 'Enchanted Redstone',
      'ENCHANTED_SAND': 'Enchanted Sand',
      'ENCHANTED_SPIDER_EYE': 'Enchanted Spider Eye',
      'ENCHANTED_SUGAR_CANE': 'Enchanted Sugar Cane',
      'ENCHANTMENT_TABLE': 'Enchantment Table',
      'ENDER_PEARL': 'Ender Pearl',
      'END_BIOME_STICK': 'End Biome Stick',
      'END_STONE_BOW': 'End Stone Bow',
      'EXPLOSIVE_MINECART': 'Minecart with TNT',
      'FAIRY_HELMET': 'Fairy\'s Fedora',
      'FANCY_TUXEDO_CHESTPLATE': 'Fancy Tuxedo Jacket',
      'FARMING_1_PORTAL': 'Portal to the Barn',
      'FARM_ARMOR_CHESTPLATE': 'Farm Armor Chestplate',
      'FARM_SUIT_HELMET': 'Farm Suit Helmet',
      'FEATHER_TALISMAN': 'Feather Talisman',
      'FIREPLACE': 'Fireplace',
      'FISH_HAT': 'Fish Hat',
      'FLOWER_POT_ITEM': 'Flower Pot',
      'FORAGING_1_PORTAL': 'Portal to Birch Park',
      'FOREST_BIOME_STICK': 'Forest Biome Stick',
      'FROZEN_BLAZE_HELMET': 'Frozen Blaze Helmet',
      'FURNACE_PLUS': 'Furnace+',
      'GHOST_BOOK': 'Ghost Book',
      'GLASS_BOTTLE': 'Glass Bottle',
      'GOLDEN_CARROT': 'Golden Carrot',
      'GOLD_BLOCK': 'Block of Gold',
      'GOLD_GIFT': 'Golden Gift',
      'GOLD_NUGGET': 'Gold Nugget',
      'GOLD_SPADE': 'Golden Shovel',
      'GOLEM_ARMOR_LEGGINGS': 'Golem Armor Leggings',
      'GRASS': 'Grass',
      'GREEN_GIFT': 'Green Gift',
      'GROWTH_BOOTS': 'Boots of Growth',
      'HALLOWEEN_CANDLES': 'Halloween Candles',
      'HARDENED_DIAMOND_LEGGINGS': 'Hardened Diamond Leggings',
      'HASTE_RING': 'Haste Ring',
      'HELMET_OF_THE_PACK': 'Helmet of the Pack',
      'HOT_POTATO_BOOK': 'Hot Potato Book',
      'HUNTER_RING': 'Hunter Ring',
      'ICE_BAIT': 'Ice Bait',
      'ILLUSION_GLASS': 'Illusion Glass',
      'INK_SACK:12': 'Light Blue Dye',
      'INK_SACK:3': 'Cocoa Beans',
      'INK_SACK:8': 'Gray Dye',
      'INTIMIDATION_TALISMAN': 'Intimidation Talisman',
      'IRON_CHEST': 'Iron Chest+',
      'IRON_HOE': 'Iron Hoe',
      'IRON_PLATE': 'Heavy Weighted Pressure Plate',
      'JACK_O_LANTERN': 'Jack o\' Lantern',
      'JUNGLE_DOOR_ITEM': 'Jungle Door',
      'KNOCKOFF_COLA': 'KnockOff™ Cola',
      'LAPIS_ARMOR_HELMET': 'Lapis Armor Helmet',
      'LARGE_BACKPACK': 'Large Backpack',
      'LAVA_TALISMAN': 'Lava Talisman',
      'LEAPING_SWORD': 'Leaping Sword',
      'LEAVES': 'Oak Leaves',
      'LEAVES_2:1': 'Dark Oak Leaves',
      'LIGHT_BAIT': 'Light Bait',
      'LOG:3': 'Jungle Wood',
      'LONG_GRASS:1': 'Long Grass',
      'MAGMA_CREAM': 'Magma Cream',
      'MASTIFF_HELMET': 'Mastiff Crown',
      'MELON_BLOCK': 'Melon',
      'MINECART': 'Minecart',
      'MINE_TALISMAN': 'Mine Affinity Talisman',
      'MINNOW_BAIT': 'Minnow Bait',
      'MUSHROOM_CHESTPLATE': 'Mushroom Chestplate',
      'MUTTON': 'Mutton',
      'NETHER_BRICK': 'Nether Bricks',
      'NETHER_WART_ISLAND': 'Nether Wart Island',
      'NOPE_THE_FISH': 'Nope the Fish',
      'OLD_DRAGON_LEGGINGS': 'Old Dragon Leggings',
      'PACKED_ICE': 'Packed Ice',
      'PERFECT_BOOTS_10': 'Perfect Boots - Tier X',
      'PERFECT_BOOTS_4': 'Perfect Boots - Tier IV',
      'PERFECT_CHESTPLATE_2': 'Perfect Chestplate - Tier II',
      'PERFECT_CHESTPLATE_7': 'Perfect Chestplate - Tier VII',
      'PERFECT_HELMET_12': 'Perfect Helmet - Tier XII',
      'PERFECT_HELMET_6': 'Perfect Helmet - Tier VI',
      'PERFECT_LEGGINGS_10': 'Perfect Leggings - Tier X',
      'PERFECT_LEGGINGS_4': 'Perfect Leggings - Tier IV',
      'PIGMAN_SWORD': 'Pigman Sword',
      'POISONOUS_POTATO': 'Poisonous Potato',
      'POTATO_ITEM': 'Potato',
      'PRESENTS': 'Present Stack',
      'PRISMARINE_BLADE': 'Prismarine Blade',
      'PROMISING_AXE': 'Promising Axe',
      'PROTECTOR_DRAGON_HELMET': 'Protector Dragon Helmet',
      'PUMPKIN': 'Pumpkin',
      'PUMPKIN_PIE': 'Pumpkin Pie',
      'QUARTZ_BLOCK:1': 'Chiseled Quartz Block',
      'QUARTZ_STAIRS': 'Quartz Stairs',
      'RADIANT_POWER_ORB': 'Radiant Power Orb',
      'RAW_FISH': 'Raw Fish',
      'REAPER_SCYTHE': 'Reaper Scythe',
      'RECORD_12': 'Music Disc - Wait',
      'RECORD_7': 'Music Disc - Mellohi',
      'REDSTONE_CHEST': 'Redstone Chest+',
      'RED_CLAW_ARTIFACT': 'Red Claw Artifact',
      'RED_MUSHROOM': 'Red Mushroom',
      'RED_ROSE:3': 'Azure Bluet',
      'RED_ROSE:8': 'Oxeye Daisy',
      'RED_TENT': 'Red Tent',
      'REVENANT_FLESH': 'Revenant Flesh',
      'RING_POTION_AFFINITY': 'Potion Affinity Ring',
      'ROOKIE_HOE': 'Rookie Hoe',
      'SADDLE': 'Saddle',
      'SANDSTONE:2': 'Smooth Sandstone',
      'SAPLING:1': 'Spruce Sapling',
      'SAVANA_BIOME_STICK': 'Savanna Biome Stick',
      'SCORPION_FOIL': 'Scorpion Foil',
      'SEA_CREATURE_RING': 'Sea Creature Ring',
      'SHAMAN_SWORD': 'Shaman Sword',
      'SILENT_PEARL': 'Silent Pearl',
      'SKELETON_HELMET': 'Skeleton\'s Helmet',
      'SKULL_PERSONALITY': 'Skull Minion Skin',
      'SLEEPING_EYE': 'Sleeping Eye',
      'SMALL_BACKPACK': 'Small Backpack',
      'SMOOTH_BRICK:1': 'Mossy Stone Bricks',
      'SMOOTH_STAIRS': 'Stone Brick Stairs',
      'SNOW_BLASTER': 'Frosty the Snow Blaster',
      'SNOW_SUIT_HELMET': 'Snow Suit Helmet',
      'SPEEDSTER_BOOTS': 'Speedster Boots',
      'SPEED_TALISMAN': 'Speed Talisman',
      'SPIDER_HAT': 'Spider Hat',
      'SPIRIT_MASK': 'Spirit Mask',
      'SPONGE_LEGGINGS': 'Sponge Leggings',
      'SPOOKY_DISC': 'Spooky Disc',
      'SPRAY_CAN': 'Spray Can',
      'SQUID_BOOTS': 'Squid Boots',
      'STAINED_CLAY:10': 'Purple Hardened Clay',
      'STAINED_CLAY:2': 'Magenta Hardened Clay',
      'STAINED_CLAY:9': 'Cyan Hardened Clay',
      'STAINED_GLASS:14': 'Red Stained Glass',
      'STAINED_GLASS:8': 'Light Gray Stained Glass',
      'STAINED_GLASS_PANE:13': 'Green Stained Glass Pane',
      'STAINED_GLASS_PANE:4': 'Yellow Stained Glass Pane',
      'STEP:5': 'Stone Brick Slab',
      'STOCK_OF_STONKS': 'Stock of Stonks',
      'STONE:4': 'Polished Diorite',
      'STONE_AXE': 'Stone Axe',
      'STONE_PLATE': 'Stone Pressure Plate',
      'STOOL': 'Stool',
      'ANVIL': 'Anvil',
      'ARMOR_OF_MAGMA_BOOTS': 'Armor of Magma Boots',
      'ARMOR_STAND': 'Armor Stand',
      'AUGER_ROD': 'Auger Rod',
      'BATTLE_DISC': 'Battle Disc',
      'BAT_PERSON_HELMET': 'Bat Person Helmet',
      'BEACH_BALL': 'Beach Ball',
      'BED': 'Bed',
      'BIRCH_FENCE': 'Birch Fence',
      'BLACKSMITH_PLUS': 'Blacksmith+',
      'BLAZE_LEGGINGS': 'Blaze Leggings',
      'BLUE_ICE_HUNK': 'Hunk of Blue Ice',
      'BOOKSHELF': 'Bookshelf',
      'BRICK': 'Bricks',
      'BUCKET': 'Bucket',
      'CACTUS_HELMET': 'Cactus Helmet',
      'CANDY_ARTIFACT': 'Candy Artifact',
      'CARPET': 'Carpet',
      'CARPET:15': 'Black Carpet',
      'CARPET:8': 'Light Gray Carpet',
      'CAULDRON': 'Cauldron',
      'CHAINMAIL_LEGGINGS': 'Chainmail Leggings',
      'CHEAP_TUXEDO_CHESTPLATE': 'Cheap Tuxedo Jacket',
      'CHICKEN_HEAD': 'Chicken Head',
      'CLOWNFISH_HAT': 'Clownfish Hat',
      'COBBLESTONE': 'Cobblestone',
      'COMPASS': 'Compass',
      'COOKIE': 'Cookie',
      'CREEPER_LEGGINGS': 'Creeper Pants',
      'CRYSTAL_FRAGMENT': 'Crystal Fragment',
      'DANGER_3_PORTAL': 'Portal to The End',
      'DARK_OAK_STAIRS': 'Dark Oak Wood Stairs',
      'DECENT_COFFEE': 'Decent Coffee',
      'DEVOUR_RING': 'Devour Ring',
      'DIAMOND_BOOTS': 'Diamond Boots',
      'DIAMOND_LEGGINGS': 'Diamond Leggings',
      'DIAMOND_SWORD': 'Diamond Sword',
      'DIRT': 'Dirt',
      'DIVER_BOOTS': 'Diver\'s Boots',
      'DOUBLE_PLANT': 'Sunflower',
      'DROPPER': 'Dropper',
      'ELEGANT_TUXEDO_BOOTS': 'Elegant Tuxedo Oxfords',
      'EMBER_FRAGMENT': 'Ember Fragment',
      'EMERALD_ARMOR_BOOTS': 'Emerald Armor Boots',
      'EMERALD_BLOCK': 'Block of Emerald',
      'ENCHANTED_BAKED_POTATO': 'Enchanted Baked Potato',
      'ENCHANTED_BONE_MEAL': 'Enchanted Bone Meal',
      'ENCHANTED_CACTUS': 'Enchanted Cactus',
      'ENCHANTED_CHARCOAL': 'Enchanted Charcoal',
      'ENCHANTED_COBBLESTONE': 'Enchanted Cobblestone',
      'ENCHANTED_COOKIE': 'Enchanted Cookie',
      'ENCHANTED_EGG': 'Enchanted Egg',
      'ENCHANTED_EYE_OF_ENDER': 'Enchanted Eye of Ender',
      'ENCHANTED_GHAST_TEAR': 'Enchanted Ghast Tear',
      'ENCHANTED_GOLDEN_CARROT': 'Enchanted Golden Carrot',
      'ENCHANTED_HOPPER': 'Enchanted Hopper',
      'ENCHANTED_IRON': 'Enchanted Iron',
      'ENCHANTED_LAPIS_LAZULI_BLOCK': 'Enchanted Lapis Block',
      'ENCHANTED_MELON_BLOCK': 'Enchanted Melon Block',
      'ENCHANTED_PACKED_ICE': 'Enchanted Packed Ice',
      'ENCHANTED_POTATO': 'Enchanted Potato',
      'ENCHANTED_QUARTZ': 'Enchanted Quartz',
      'ENCHANTED_RAW_BEEF': 'Enchanted Raw Beef',
      'ENCHANTED_REDSTONE_BLOCK': 'Enchanted Redstone Block',
      'ENCHANTED_SEEDS': 'Enchanted Seeds',
      'ENCHANTED_SPONGE': 'Enchanted Sponge',
      'ENCHANTED_WATER_LILY': 'Enchanted Lily Pad',
      'ENDERMAN_MASK': 'Enderman Mask',
      'ENDER_PLUS': 'Ender Chest+',
      'END_BOOTS': 'Ender Boots',
      'END_STONE_SWORD': 'End Stone Sword',
      'EXP_BOTTLE': 'Experience Bottle',
      'FAIRY_LEGGINGS': 'Fairy\'s Trousers',
      'FANCY_TUXEDO_LEGGINGS': 'Fancy Tuxedo Pants',
      'FARMING_2_PORTAL': 'Portal to Mushroom Island',
      'FARM_ARMOR_HELMET': 'Farm Armor Helmet',
      'FARM_SUIT_LEGGINGS': 'Farm Suit Leggings',
      'FENCE': 'Oak Fence',
      'FIREWORK': 'Firework Rocket',
      'FLAMING_SWORD': 'Flaming Sword',
      'FLYCATCHER_UPGRADE': 'Flycatcher',
      'FORAGING_2_PORTAL': 'Portal to Spruce Woods',
      'FOUL_FLESH': 'Foul Flesh',
      'FROZEN_BLAZE_LEGGINGS': 'Frozen Blaze Leggings',
      'GAME_BREAKER': 'Game Breaker',
      'GIFT_COMPASS': 'Gift Compass',
      'GLOWSTONE': 'Glowstone',
      'GOLDEN_POWDER': 'Golden Powder',
      'GOLD_BOOTS': 'Golden Boots',
      'GOLD_HELMET': 'Golden Helmet',
      'GOLD_ORE': 'Gold Ore',
      'GOLD_SWORD': 'Golden Sword',
      'GOLEM_SWORD': 'Golem Sword',
      'GRAVEL': 'Gravel',
      'GREEN_RECORD': 'Music Disc - Cat',
      'GROWTH_CHESTPLATE': 'Chestplate of Growth',
      'HAMSTER_WHEEL': 'Hamster Wheel',
      'HARD_CLAY': 'Hardened Clay',
      'HAY_BED': 'Hay Bed',
      'HILT_OF_TRUE_ICE': 'Hilt of True Ice',
      'HUB_PORTAL': 'Portal to the Hub',
      'HUNTER_TALISMAN': 'Hunter Talisman',
      'ICE_CREAM_PERSONALITY': 'Ice Cream Minion Skin',
      'INK_SACK': 'Ink Sack',
      'INK_SACK:13': 'Magenta Dye',
      'INK_SACK:4': 'Lapis Lazuli',
      'INK_SACK:9': 'Pink Dye',
      'IRON_AXE': 'Iron Axe',
      'IRON_CHESTPLATE': 'Iron Chestplate',
      'IRON_INGOT': 'Iron Ingot',
      'IRON_SPADE': 'Iron Shovel',
      'JINGLE_BELLS': 'Jingle Bells',
      'JUNGLE_FENCE': 'Jungle Fence',
      'KRAMPUS_HELMET': 'Krampus Helmet',
      'LAPIS_ARMOR_LEGGINGS': 'Lapis Armor Leggings',
      'LARGE_BED': 'Large Bed',
      'LEAFLET_BOOTS': 'Leaflet Sandals',
      'LEASH': 'Lead',
      'LEAVES:1': 'Spruce Leaves',
      'LOG': 'Oak Wood',
      'LOG_2': 'Acacia Wood',
      'LONG_GRASS:2': 'Fern',
      'MAGMA_CUBE_HEAD': 'Magma Cube Head',
      'MASTIFF_LEGGINGS': 'Mastiff Leggings',
      'MELON_PERSONALITY': 'Melon Minion Skin',
      'MINER_OUTFIT_BOOTS': 'Miner\'s Outfit Boots',
      'MINING_1_PORTAL': 'Portal to the Gold Mine',
      'MONSTER_EGG': 'Spawn Egg',
      'MUSHROOM_HELMET': 'Mushroom Helmet',
      'MYCEL': 'Mycelium',
      'NETHER_BRICK_ITEM': 'Nether Brick',
      'NEW_YEAR_CAKE': 'New Year Cake',
      'NOTE_BLOCK': 'Noteblock',
      'OBSIDIAN_CHESTPLATE': 'Obsidian Chestplate',
      'OLD_FRAGMENT': 'Old Dragon Fragment',
      'PAINTING': 'Painting',
      'PERFECT_BOOTS_11': 'Perfect Boots - Tier XI',
      'PERFECT_BOOTS_5': 'Perfect Boots - Tier V',
      'PERFECT_CHESTPLATE_1': 'Perfect Chestplate - Tier I',
      'PERFECT_CHESTPLATE_3': 'Perfect Chestplate - Tier III',
      'PERFECT_CHESTPLATE_8': 'Perfect Chestplate - Tier VIII',
      'PERFECT_HELMET_2': 'Perfect Helmet - Tier II',
      'PERFECT_LEGGINGS_5': 'Perfect Leggings - Tier V',
      'PERSONAL_BANK_ITEM': 'Personal Bank Item',
      'PIGS_FOOT': 'Pig\'s Foot',
      'POLISHED_PEBBLE': 'Polished Pebble',
      'POTION': 'Speed VII Potion',
      'PRISMARINE': 'Prismarine',
      'PRISMARINE_BOW': 'Prismarine Bow',
      'PROMISING_PICKAXE': 'Promising Pickaxe',
      'PROTECTOR_DRAGON_LEGGINGS': 'Protector Dragon Leggings',
      'PUMPKIN_BOOTS': 'Pumpkin Boots',
      'PUMPKIN_SEEDS': 'Pumpkin Seeds',
      'QUARTZ_BLOCK:2': 'Pillar Quartz Block',
      'RABBIT': 'Raw Rabbit',
      'RAIDER_AXE': 'Raider Axe',
      'RAW_FISH:1': 'Raw Salmon',
      'REAPER_SWORD': 'Reaper Falchion',
      'RECORD_3': 'Music Disc - Blocks',
      'RECORD_8': 'Music Disc - Stal',
      'REDSTONE_COMPARATOR': 'Comparator',
      'RED_CLAW_EGG': 'Red Claw Egg',
      'RED_ROSE': 'Poppy',
      'RED_ROSE:4': 'Red Tulip',
      'REMNANT_OF_THE_EYE': 'Remnant of the Eye',
      'REVENANT_LEGGINGS': 'Revenant Leggings',
      'ROGUE_SWORD': 'Rogue Sword',
      'ROOKIE_PICKAXE': 'Rookie Pickaxe',
      'SALMON_HAT': 'Salmon Hat',
      'SAPLING:2': 'Birch Sapling',
      'SAVANA_BOW': 'Savanna Bow',
      'SCULPTORS_AXE': 'Sculptor\'s Axe',
      'SEA_CREATURE_TALISMAN': 'Sea Creature Talisman',
      'SHEARS': 'Shears',
      'SILKY_LICHEN': 'Silky Lichen',
      'SKELETON_TALISMAN': 'Skeleton Talisman',
      'SKYBLOCK_BENCH': 'Dark Oak Bench',
      'SLIME_BALL': 'Slimeball',
      'SMALL_ENCHANTED_CHEST': 'Small Storage',
      'SNOW': 'Snow',
      'SNOW_BLOCK': 'Snow Block',
      'SNOW_SUIT_LEGGINGS': 'Snow Suit Leggings',
      'SPEEDSTER_CHESTPLATE': 'Speedster Chestplate',
      'SPIDER_ARTIFACT': 'Spider Artifact',
      'SPIDER_RING': 'Spider Ring',
      'SPONGE': 'Sponge',
      'SPONGE_ROD': 'Sponge Rod',
      'SPOOKY_HELMET': 'Spooky Helmet',
      'SPRUCE_DOOR_ITEM': 'Spruce Door',
      'SQUID_HAT': 'Squid Hat',
      'STAINED_CLAY:11': 'Blue Hardened Clay',
      'STAINED_CLAY:3': 'Light Blue Hardened Clay',
      'STAINED_GLASS': 'White Stained Glass',
      'STAINED_GLASS:15': 'Black Stained Glass',
      'STAINED_GLASS_PANE': 'White Stained Glass Pane',
      'STAINED_GLASS_PANE:14': 'Red Stained Glass Pane',
      'STAINED_GLASS_PANE:5': 'Lime Stained Glass Pane',
      'STEP': 'Stone Slab',
      'STEP:6': 'Nether Brick Slab',
      'STONE': 'Stone',
      'STONE:5': 'Andesite',
      'STONE_BRIDGE': 'Stone Platform',
      'STONE_SLAB2': 'Red Sandstone Slab',
      'STORAGE_MINECART': 'Minecart with Chest',
      'STRONG_DRAGON_LEGGINGS': 'Strong Dragon Leggings',
      'SUMMONING_EYE': 'Summoning Eye',
      'SUPERIOR_DRAGON_HELMET': 'Superior Dragon Helmet',
      'SURVIVOR_CUBE': 'Survivor Cube',
      'TANK_MINER_CHESTPLATE': 'Miner Chestplate',
      'TARANTULA_HELMET': 'Tarantula Helmet',
      'TELEPORT_PAD': 'Teleport Pad',
      'TITANIC_EXP_BOTTLE': 'Titanic Experience Bottle',
      'TRAPPED_CHEST': 'Trapped Chest',
      'TRUE_ESSENCE': 'True Essence',
      'UNSTABLE_DRAGON_BOOTS': 'Unstable Dragon Boots',
      'VACCINE_TALISMAN': 'Vaccine Talisman',
      'VOODOO_DOLL': 'Voodoo Doll',
      'WATCH': 'Clock',
      'WEAK_WOLF_CATALYST': 'Weak Wolf Catalyst',
      'WHALE_BAIT': 'Whale Bait',
      'WISE_DRAGON_BOOTS': 'Wise Dragon Boots',
      'WITHER_ARTIFACT': 'Wither Artifact',
      'WOLF_TOOTH': 'Wolf Tooth',
      'WOOD:4': 'Acacia Wood Plank',
      'WOOD_AXE': 'Wooden Axe',
      'WOOD_PICKAXE': 'Wooden Pickaxe',
      'WOOD_STEP': 'Oak Wood Slab',
      'WOOD_STEP:5': 'Dark Oak Wood Slab',
      'WOOL:1': 'Orange Wool',
      'WOOL:14': 'Red Wool',
      'WOOL:5': 'Lime Wool',
      'WORKBENCH': 'Crafting Table',
      'YOUNG_DRAGON_BOOTS': 'Young Dragon Boots',
      'ZOMBIE_ARTIFACT': 'Zombie Artifact',
      'ZOMBIE_HEART': 'Zombie\'s Heart',
      'ZOMBIE_TALISMAN': 'Zombie Talisman',
      'ANVIL:1': 'Slightly Damaged Anvil',
      'ARMOR_OF_MAGMA_CHESTPLATE': 'Armor of Magma Chestplate',
      'ARROW': 'Arrow',
      'AUTO_SMELTER': 'Auto Smelter',
      'BAT_ARTIFACT': 'Bat Artifact',
      'BAT_PERSON_LEGGINGS': 'Bat Person Leggings',
      'BEACH_BALL_PERSONALITY': 'Beach Ball Minion Skin',
      'BEHEADED_HORROR': 'Beheaded Horror',
      'BIRCH_FENCE_GATE': 'Birch Fence Gate',
      'BLAZE_BOOTS': 'Blaze Boots',
      'BLAZE_POWDER': 'Blaze Powder',
      'BOAT': 'Boat',
      'BOOK_AND_QUILL': 'Book and Quill',
      'BOWL': 'Bowl',
      'BRICK_STAIRS': 'Brick Stairs',
      'BUDGET_HOPPER': 'Budget Hopper',
      'CACTUS_LEGGINGS': 'Cactus Leggings',
      'CANDY_BOWL': 'Candy Bowl',
      'CARPET:1': 'Orange Carpet',
      'CARPET:2': 'Magenta Carpet',
      'CARROT': 'Carrots',
      'CAULDRON_ITEM': 'Cauldron',
      'CHALLENGE_ROD': 'Challenging Rod',
      'CHEAP_TUXEDO_LEGGINGS': 'Cheap Tuxedo Pants',
      'CLAY': 'Clay',
      'COAL': 'Coal',
      'COBBLESTONE_STAIRS': 'Cobblestone Stairs',
      'COFFEE_TABLE': 'Coffee Table',
      'COOKED_BEEF': 'Cooked Beef',
      'COW_HEAD': 'Cow Head',
      'CROOKED_ARTIFACT': 'Crooked Artifact',
      'CRYSTAL_HELMET': 'Crystal Helmet',
      'DARK_BAIT': 'Dark Bait',
      'DAYLIGHT_DETECTOR': 'Daylight Detector',
      'DEEP_OCEAN_BIOME_STICK': 'Deep Ocean Biome Stick',
      'DIAMOND': 'Diamond',
      'DIAMOND_CHEST': 'Diamond Chest+',
      'DIAMOND_ORE': 'Diamond Ore',
      'DIGESTED_MOSQUITO': 'Digested Mosquito',
      'DIRT:1': 'Coarse Dirt',
      'DIVER_CHESTPLATE': 'Diver\'s Shirt',
      'DOUBLE_PLANT:1': 'Lilac',
      'DR_PAPER': 'Dctr. Paper',
      'ELEGANT_TUXEDO_CHESTPLATE': 'Elegant Tuxedo Jacket',
      'EMBER_HELMET': 'Ember Helmet',
      'EMERALD_ARMOR_CHESTPLATE': 'Emerald Armor Chestplate',
      'EMERALD_CHEST': 'Emerald Chest+',
      'ENCHANTED_BIRCH_LOG': 'Enchanted Birch Wood',
      'ENCHANTED_BOOK': 'Enchanted Book',
      'ENCHANTED_CACTUS_GREEN': 'Enchanted Cactus Green',
      'ENCHANTED_CLAY_BALL': 'Enchanted Clay',
      'ENCHANTED_COCOA': 'Enchanted Cocoa Bean',
      'ENCHANTED_DANDELION': 'Enchanted Dandelion',
      'ENCHANTED_EMERALD': 'Enchanted Emerald',
      'ENCHANTED_FEATHER': 'Enchanted Feather',
      'ENCHANTED_GLISTERING_MELON': 'Enchanted Glistering Melon',
      'ENCHANTED_GOLD_BLOCK': 'Enchanted Gold Block',
      'ENCHANTED_HUGE_MUSHROOM_1': 'Enchanted Brown Mushroom Block',
      'ENCHANTED_IRON_BLOCK': 'Enchanted Iron Block',
      'ENCHANTED_LAVA_BUCKET': 'Enchanted Lava Bucket',
      'ENCHANTED_MUTTON': 'Enchanted Mutton',
      'ENCHANTED_PAPER': 'Enchanted Paper',
      'ENCHANTED_PRISMARINE_CRYSTALS': 'Enchanted Prismarine Crystals',
      'ENCHANTED_QUARTZ_BLOCK': 'Enchanted Quartz Block',
      'ENCHANTED_RAW_CHICKEN': 'Enchanted Raw Chicken',
      'ENCHANTED_REDSTONE_LAMP': 'Enchanted Redstone Lamp',
      'ENCHANTED_SLIME_BALL': 'Enchanted Slimeball',
      'ENCHANTED_SPRUCE_LOG': 'Enchanted Spruce Wood',
      'ENCHANTED_WET_SPONGE': 'Enchanted Wet Sponge',
      'ENDER_ARTIFACT': 'Ender Artifact',
      'ENDER_PORTAL_FRAME': 'End Portal Frame',
      'END_CHESTPLATE': 'Ender Chestplate',
      'END_SWORD': 'End Sword',
      'EYE_OF_ENDER': 'Eye of Ender',
      'FANCY_FLOWER_POT': 'Flower Pot',
      'FARMER_BOOTS': 'Farmer Boots',
      'FARMING_ISLAND': 'Farming Island',
      'FARM_ARMOR_LEGGINGS': 'Farm Armor Leggings',
      'FEATHER': 'Feather',
      'FENCE_GATE': 'Oak Fence Gate',
      'FIREWORK_CHARGE': 'Firework Star',
      'FLINT': 'Flint',
      'FLYING_BATS': 'Flying Bats',
      'FORAGING_3_PORTAL': 'Portal to Jungle Island',
      'FROSTY_SNOW_BALL': 'Frosty Snowball',
      'FROZEN_CHICKEN': 'Frozen Chicken',
      'GARLAND': 'Garland',
      'GIFT_THE_FISH': 'Gift the Fish',
      'GLOWSTONE_DUST': 'Glowstone Dust',
      'GOLDEN_TOOTH': 'Golden Tooth',
      'GOLD_CANDY': 'Golden Treat',
      'GOLD_HOE': 'Golden Hoe',
      'GOLD_PICKAXE': 'Golden Pickaxe',
      'GOLEM_ARMOR_BOOTS': 'Golem Armor Boots',
      'GRANDFATHER_CLOCK': 'Grandfather Clock',
      'GRAVITY_TALISMAN': 'Gravity Talisman',
      'GRILLED_PORK': 'Cooked Porkchop',
      'GROWTH_HELMET': 'Helmet of Growth',
      'HARDENED_DIAMOND_BOOTS': 'Hardened Diamond Boots',
      'HARD_GLASS': 'Hard Glass',
      'HAY_BLOCK': 'Hay Bale',
      'HOPPER': 'Hopper',
      'HUGE_MUSHROOM_1': 'Brown Mushroom Block',
      'HURRICANE_BOW': 'Hurricane Bow',
      'ICE_HUNK': 'Hunk of Ice',
      'INK_SACK:1': 'Rose Red',
      'INK_SACK:14': 'Orange Dye',
      'INK_SACK:5': 'Purple Dye',
      'INK_WAND': 'Ink Wand',
      'IRON_BARDING': 'Iron Horse Armor',
      'IRON_DOOR': 'Iron Door',
      'IRON_LEGGINGS': 'Iron Leggings',
      'IRON_SWORD': 'Iron Sword',
      'JUKEBOX': 'Jukebox',
      'JUNGLE_FENCE_GATE': 'Jungle Fence Gate',
      'LADDER': 'Ladder',
      'LAPIS_BLOCK': 'Lapis Lazuli Block',
      'LARGE_ENCHANTED_CHEST': 'Large Storage',
      'LEAFLET_CHESTPLATE': 'Leaflet Tunic',
      'LEATHER': 'Leather',
      'LEATHER_CHESTPLATE': 'Leather Chestplate',
      'LEAVES:2': 'Birch Leaves',
      'LEGEND_ROD': 'Rod of Legends',
      'LOG:0': 'Oak Wood',
      'LOG_2:1': 'Dark Oak Wood',
      'MAGICAL_WATER_BUCKET': 'Magical Water Bucket',
      'MAGNETIC_TALISMAN': 'Magnetic Talisman',
      'MEDIUM_BACKPACK': 'Medium Backpack',
      'MELON_SEEDS': 'Melon Seeds',
      'MINER_OUTFIT_CHESTPLATE': 'Miner\'s Outfit Chestplate',
      'MINING_2_PORTAL': 'Portal to the Deep Caverns',
      'MOSQUITO_BOW': 'Mosquito Bow',
      'MUSHROOM_LEGGINGS': 'Mushroom Leggings',
      'NAME_TAG': 'Name Tag',
      'NETHER_BRICK_STAIRS': 'Nether Bricks Stairs',
      'NEW_YEAR_CAKE_BAG': 'New Year Cake Bag',
      'NUTCRACKER': 'Nutcracker',
      'OLD_DRAGON_BOOTS': 'Old Dragon Boots',
      'ORNATE_ZOMBIE_SWORD': 'Ornate Zombie Sword',
      'PAPER': 'Paper',
      'PERFECT_BOOTS_12': 'Perfect Boots - Tier XII',
      'PERFECT_BOOTS_6': 'Perfect Boots - Tier VI',
      'PERFECT_CHESTPLATE_10': 'Perfect Chestplate - Tier X',
      'PERFECT_CHESTPLATE_4': 'Perfect Chestplate - Tier IV',
      'PERFECT_CHESTPLATE_9': 'Perfect Chestplate - Tier IX',
      'PERFECT_HELMET_3': 'Perfect Helmet - Tier III',
      'PERFECT_HELMET_8': 'Perfect Helmet - Tier VIII',
      'PERFECT_LEGGINGS_12': 'Perfect Leggings - Tier XII',
      'PERFECT_LEGGINGS_6': 'Perfect Leggings - Tier VI',
      'PET': '[Lvl 1] Rabbit',
      'PISTON_BASE': 'Piston',
      'POND_ISLAND': 'Pond Island',
      'POTION_AFFINITY_TALISMAN': 'Potion Affinity Talisman',
      'PRISMARINE:1': 'Prismarine Bricks',
      'PRISMARINE_CRYSTALS': 'Prismarine Crystals',
      'PROMISING_SPADE': 'Promising Shovel',
      'PROTECTOR_FRAGMENT': 'Protector Dragon Fragment',
      'PUMPKIN_CHESTPLATE': 'Pumpkin Chestplate',
      'PURPLE_CANDY': 'Purple Candy',
      'RABBIT_FOOT': 'Rabbit\'s Foot',
      'RAILS': 'Rail',
      'RAW_FISH:2': 'Clownfish',
      'RECLUSE_FANG': 'Recluse Fang',
      'RECORD_4': 'Music Disc - Chirp',
      'RECORD_9': 'Music Disc - Strad',
      'REDSTONE_LAMP_OFF': 'Redstone Lamp',
      'RED_CLAW_RING': 'Red Claw Ring',
      'RED_ROSE:1': 'Blue Orchid',
      'RED_ROSE:5': 'Orange Tulip',
      'RED_SANDSTONE': 'Red Sandstone',
      'REVENANT_BOOTS': 'Revenant Boots',
      'REVENANT_SWORD': 'Revenant Falchion',
      'ROOFED_FOREST_BIOME_STICK': 'Roofed Forest Biome Stick',
      'ROTTEN_FLESH': 'Rotten Flesh',
      'SAND': 'Sand',
      'SANDCASTLE_PERSONALITY': 'Sandcastle Minion Skin',
      'SANDSTONE_STAIRS': 'Sandstone Stairs',
      'SAPLING:3': 'Jungle Sapling',
      'SCARECROW': 'Scarecrow',
      'SCYTHE_BLADE': 'Scythe Blade',
      'SEA_LANTERN': 'Sea Lantern',
      'SHRIMP_THE_FISH': 'Shrimp the Fish',
      'SILK_EDGE_SWORD': 'Silk-Edge Sword',
      'SKULL_CHEST': 'Skull Chest++',
      'SKYBLOCK_CHAIR': 'Dark Oak Chair',
      'SLIME_BLOCK': 'Slime Block',
      'SMALL_SHELVES': 'Small Shelves',
      'SMOOTH_BRICK:2': 'Cracked Stone Bricks',
      'SNOWFLAKE_THE_FISH': 'Flake the Fish',
      'SNOW_CANNON': 'Frosty the Snow Cannon',
      'SOLAR_PANEL': 'Solar Panel',
      'SPEEDSTER_HELMET': 'Speedster Helmet',
      'SPIDER_BOOTS': 'Spider\'s Boots',
      'SPIDER_SWORD': 'Spider Sword',
      'SPONGE_BOOTS': 'Spongy Shoes',
      'SPOOKY_BAIT': 'Spooky Bait',
      'SPOOKY_LEGGINGS': 'Spooky Leggings',
      'SPRUCE_FENCE': 'Spruce Fence',
      'STACKED_PUMPKINS': 'Stacked Pumpkins',
      'STAINED_CLAY:12': 'Brown Hardened Clay',
      'STAINED_CLAY:4': 'Yellow Hardened Clay',
      'STAINED_GLASS:1': 'Orange Stained Glass',
      'STAINED_GLASS:2': 'Magenta Stained Glass',
      'STAINED_GLASS_PANE:1': 'Orange Stained Glass Pane',
      'STAINED_GLASS_PANE:15': 'Black Stained Glass Pane',
      'STAINED_GLASS_PANE:6': 'Pink Stained Glass Pane',
      'STEP:1': 'Sandstone Slab',
      'STEP:7': 'Quartz Slab',
      'STONE:1': 'Granite',
      'STONE:6': 'Polished Andesite',
      'STONE_BUTTON': 'Stone Button',
      'STONE_SPADE': 'Stone Shovel',
      'STRING': 'String',
      'STRONG_FRAGMENT': 'Strong Dragon Fragment',
      'SUN_PERSONALITY': 'Sun Minion Skin',
      'SUPERIOR_DRAGON_LEGGINGS': 'Superior Dragon Leggings',
      'SWEET_AXE': 'Sweet Axe',
      'TANK_MINER_HELMET': 'Miner Helmet',
      'TARANTULA_LEGGINGS': 'Tarantula Leggings',
      'TEPID_GREEN_TEA': 'Tepid Green Tea',
      'TNT': 'TNT',
      'TRAP_DOOR': 'Wooden Trapdoor',
      'TUTTI_FRUTTI_POISON': 'Tutti-Frutti Flavored Poison',
      'UNSTABLE_DRAGON_CHESTPLATE': 'Unstable Dragon Chestplate',
      'VAMPIRE_MASK': 'Vampire Mask',
      'WATER_BUCKET': 'Water Bucket',
      'WEAPON_RACK': 'Weapon Rack',
      'WHEAT': 'Wheat',
      'WISE_DRAGON_CHESTPLATE': 'Wise Dragon Chestplate',
      'WITHER_BOW': 'Wither Bow',
      'WOOD': 'Oak Wood Plank',
      'WOOD:5': 'Dark Oak Wood Plank',
      'WOOD_BUTTON': 'Wooden Button',
      'WOOD_PLATE': 'Wooden Pressure Plate',
      'WOOD_STEP:1': 'Spruce Wood Slab',
      'WOOL:10': 'Purple Wool',
      'WOOL:15': 'Black Wool',
      'WOOL:6': 'Pink Wool',
      'WRAPPED_GIFT_FOR_JULIETTE': 'Secret Gift for Juliette',
      'YOUNG_DRAGON_CHESTPLATE': 'Young Dragon Chestplate',
      'ZOMBIE_BOOTS': 'Zombie Boots',
      'ZOMBIE_LEGGINGS': 'Zombie Leggings',
      'ARMOR_OF_MAGMA_HELMET': 'Armor of Magma Helmet',
      'ARTIFACT_POTION_AFFINITY': 'Potion Affinity Artifact',
      'BAIT_RING': 'Bait Ring',
      'BAT_FIREWORK': 'Bat Firework',
      'BAT_RING': 'Bat Ring',
      'BEACH_CHAIR': 'Beach Chair',
      'BEST_WEAPON_RACK': 'Weapon Rack+',
      'BIRCH_FOREST_BIOME_STICK': 'Birch Forest Biome Stick',
      'BLAZE_CHESTPLATE': 'Blaze Chestplate',
      'BLAZE_ROD': 'Blaze Rod',
      'BONE': 'Bone',
      'BOOTS_OF_THE_PACK': 'Boots of the Pack',
      'BREAD': 'Bread',
      'BRIDGE_EGG': 'Bridge Egg',
      'CACTUS': 'Cactus',
      'CAKE': 'Cake',
      'CANDY_RING': 'Candy Ring',
      'CARPET:11': 'Blue Carpet',
      'CARPET:3': 'Light Blue Carpet',
      'CARROT_BAIT': 'Carrot Bait',
      'CHAINMAIL_BOOTS': 'Chainmail Boots',
      'CHAMP_ROD': 'Rod of Champions',
      'CHEST': 'Chest',
      'CLAY_BALL': 'Clay',
      'COAL:1': 'Charcoal',
      'COBBLE_WALL': 'Cobblestone Wall',
      'COIN_TALISMAN': 'Talisman of Coins',
      'COOKED_CHICKEN': 'Cooked Chicken',
      'CRACKED_PIGGY_BANK': 'Cracked Piggy Bank',
      'CRYSTALLIZED_HEART': 'Crystallized Heart',
      'CRYSTAL_LEGGINGS': 'Crystal Leggings',
      'DARK_OAK_DOOR_ITEM': 'Dark Oak Door',
      'DAY_SAVER': 'Day Saver',
      'DESERT_BIOME_STICK': 'Desert Biome Stick',
      'DIAMOND_AXE': 'Diamond Axe',
      'DIAMOND_CHESTPLATE': 'Diamond Chestplate',
      'DIAMOND_PICKAXE': 'Diamond Pickaxe',
      'DINING_CHAIR': 'Dining Chair',
      'DIRT:2': 'Podzol',
      'DIVER_FRAGMENT': 'Emperor\'s Skull',
      'DOUBLE_PLANT:2': 'Double Tallgrass',
      'EDIBLE_MACE': 'Edible Mace',
      'ELEGANT_TUXEDO_LEGGINGS': 'Elegant Tuxedo Pants',
      'EMBER_LEGGINGS': 'Ember Leggings',
      'EMERALD_ARMOR_HELMET': 'Emerald Armor Helmet',
      'EMERALD_ORE': 'Emerald Ore',
      'ENCHANTED_BLAZE_POWDER': 'Enchanted Blaze Powder',
      'ENCHANTED_BOOKSHELF': 'Enchanted Bookshelf',
      'ENCHANTED_CAKE': 'Enchanted Cake',
      'ENCHANTED_CLOWNFISH': 'Enchanted Clownfish',
      'ENCHANTED_COOKED_FISH': 'Enchanted Cooked Fish',
      'ENCHANTED_DARK_OAK_LOG': 'Enchanted Dark Oak Wood',
      'ENCHANTED_EMERALD_BLOCK': 'Enchanted Emerald Block',
      'ENCHANTED_FERMENTED_SPIDER_EYE': 'Enchanted Fermented Spider Eye',
      'ENCHANTED_GLOWSTONE': 'Enchanted Glowstone',
      'ENCHANTED_GRILLED_PORK': 'Enchanted Grilled Pork',
      'ENCHANTED_HUGE_MUSHROOM_2': 'Enchanted Red Mushroom Block',
      'ENCHANTED_JACK_O_LANTERN': 'Lantern Helmet',
      'ENCHANTED_LEATHER': 'Enchanted Leather',
      'ENCHANTED_NETHER_STALK': 'Enchanted Nether Wart',
      'ENCHANTED_POISONOUS_POTATO': 'Enchanted Poisonous Potato',
      'ENCHANTED_PRISMARINE_SHARD': 'Enchanted Prismarine Shard',
      'ENCHANTED_RABBIT': 'Enchanted Raw Rabbit',
      'ENCHANTED_RAW_FISH': 'Enchanted Raw Fish',
      'ENCHANTED_RED_MUSHROOM': 'Enchanted Red Mushroom',
      'ENCHANTED_SLIME_BLOCK': 'Enchanted Slime Block',
      'ENCHANTED_STRING': 'Enchanted String',
      'ENCHANTED_WOOL': 'Enchanted Wool',
      'ENDER_BOW': 'Ender Bow',
      'ENDER_STONE': 'End Stone',
      'END_HELMET': 'Ender Helmet',
      'EXPERIENCE_ARTIFACT': 'Experience Artifact',
      'FAIRY_BOOTS': 'Fairy\'s Galoshes',
      'FANCY_SWORD': 'Fancy Sword',
      'FARMER_ORB': 'Farmer Orb',
      'FARMING_TALISMAN': 'Farming Talisman',
      'FARM_SUIT_BOOTS': 'Farm Suit Boots',
      'FEATHER_ARTIFACT': 'Feather Artifact',
      'FERMENTED_SPIDER_EYE': 'Fermented Spider Eye',
      'FIRE_TALISMAN': 'Fire Talisman',
      'FISH_AFFINITY_TALISMAN': 'Fish Affinity Talisman',
      'FLINT_AND_STEEL': 'Flint and Steel',
      'FLY_SWATTER': 'Fly Swatter',
      'FORAGING_4_PORTAL': 'Portal to Savanna Woodland',
      'FROZEN_BLAZE_BOOTS': 'Frozen Blaze Boots',
      'FROZEN_SCYTHE': 'Frozen Scythe',
      'GHAST_HEAD': 'Ghast Head',
      'GINGERBREAD_PERSONALITY': 'Gingerbread Man Minion Skin',
      'GOLDEN_APPLE': 'Golden Apple',
      'GOLD_AXE': 'Golden Axe',
      'GOLD_CHEST': 'Gold Chest+',
      'GOLD_INGOT': 'Gold Ingot',
      'GOLD_PLATE': 'Light Weighted Pressure Plate',
      'GOLEM_ARMOR_CHESTPLATE': 'Golem Armor Chestplate',
      'GRAND_EXP_BOTTLE': 'Grand Experience Bottle',
      'GREATER_BACKPACK': 'Greater Backpack',
      'GRINCH_PERSONALITY': 'Grinch Minion Skin',
      'GROWTH_LEGGINGS': 'Leggings of Growth',
      'HARDENED_DIAMOND_CHESTPLATE': 'Hardened Diamond Chestplate',
      'HARP': 'Personal Harp',
      'HEALING_RING': 'Healing Ring',
      'HOPPER_MINECART': 'Minecart with Hopper',
      'HUGE_MUSHROOM_2': 'Red Mushroom Block',
      'HYPIXEL_CASTLE': 'Hypixel Sandcastle',
      'ICE_LOLLY_PERSONALITY': 'Ice Lolly Minion Skin',
      'INK_SACK:10': 'Lime Dye',
      'INK_SACK:15': 'Bone Meal',
      'INK_SACK:6': 'Cyan Dye',
      'INTIMIDATION_ARTIFACT': 'Intimidation Artifact',
      'IRON_BLOCK': 'Block of Iron',
      'IRON_FENCE': 'Iron Bars',
      'IRON_ORE': 'Iron Ore',
      'IRON_TRAPDOOR': 'Iron Trapdoor',
      'JUNGLE_AXE': 'Jungle Axe',
      'JUNGLE_WOOD_STAIRS': 'Jungle Wood Stairs',
      'LAPIS_ARMOR_BOOTS': 'Lapis Armor Boots',
      'LAPIS_CHEST': 'Lapis Chest+',
      'LAUNCH_PAD': 'Launch Pad',
      'LEAFLET_HELMET': 'Leaflet Hat',
      'LEATHER_BOOTS': 'Leather Boots',
      'LEATHER_HELMET': 'Leather Helmet',
      'LEAVES:3': 'Jungle Leaves',
      'LEGGINGS_OF_THE_PACK': 'Leggings of the Pack',
      'LOG:1': 'Spruce Wood',
      'MAGIC_MUSHROOM_SOUP': 'Magical Mushroom Soup',
      'MANA_FLUX_POWER_ORB': 'Mana Flux Power Orb',
      'MAP:-121': 'Map',
      'MASTIFF_BOOTS': 'Mastiff Boots',
      'MEDIUM_ENCHANTED_CHEST': 'Medium Storage',
      'MIDAS_SWORD': 'Midas\' Sword',
      'MINER_OUTFIT_HELMET': 'Miner\'s Outfit Helmet',
      'MINION_CHAIR': 'Minion Chair',
      'MOSSY_COBBLESTONE': 'Moss Stone',
      'MUSHROOM_SOUP': 'Mushroom Soup',
      'NETHERRACK': 'Netherrack',
      'NETHER_FENCE': 'Nether Brick Fence',
      'NIGHT_SAVER': 'Night Saver',
      'OBSIDIAN': 'Obsidian',
      'OLD_DRAGON_CHESTPLATE': 'Old Dragon Chestplate',
      'OVERFLUX_CAPACITOR': 'Overflux Capacitor',
      'PEDESTAL': 'X PEDESTAL',
      'PERFECT_BOOTS_2': 'Perfect Boots - Tier II',
      'PERFECT_BOOTS_7': 'Perfect Boots - Tier VII',
      'PERFECT_CHESTPLATE_11': 'Perfect Chestplate - Tier XI',
      'PERFECT_CHESTPLATE_5': 'Perfect Chestplate - Tier V',
      'PERFECT_HELMET_1': 'Perfect Helmet - Tier I',
      'PERFECT_HELMET_4': 'Perfect Helmet - Tier IV',
      'PERFECT_LEGGINGS_2': 'Perfect Leggings - Tier II',
      'PICNIC_SET': 'Picnic Set',
      'PISTON_STICKY_BASE': 'Sticky Piston',
      'POOCH_SWORD': 'Pooch Sword',
      'POWERED_MINECART': 'Minecart with Furnace',
      'PRISMARINE:2': 'Dark Prismarine',
      'PRISMARINE_ROD': 'Prismarine Rod',
      'PROTECTOR_DRAGON_BOOTS': 'Protector Dragon Boots',
      'PUFFERFISH_HAT': 'Pufferfish Hat',
      'PUMPKIN_HELMET': 'Pumpkin Helmet',
      'QUARTZ': 'Nether Quartz',
      'RABBIT_HAT': 'Rabbit Hat',
      'RAW_BEEF': 'Raw Beef',
      'RAW_FISH:3': 'Pufferfish',
      'RECORD_10': 'Music Disc - Ward',
      'RECORD_5': 'Music Disc - Far',
      'REDSTONE': 'Redstone',
      'REDSTONE_ORE': 'Redstone Ore',
      'RED_CLAW_TALISMAN': 'Red Claw Talisman',
      'RED_ROSE:6': 'White Tulip',
      'RED_SANDSTONE:1': 'Red Chiseled Sandstone',
      'REVENANT_CATALYST': 'Revenant Catalyst',
      'REVENANT_VISCERA': 'Revenant Viscera',
      'ROOFED_FOREST_ISLAND': 'Roofed Forest Island',
      'RUNAANS_BOW': 'Runaan\'s Bow',
      'SAND:1': 'Red Sand',
      'SANDSTONE': 'Sandstone',
      'SANTA_PERSONALITY': 'Santa Minion Skin',
      'SAPLING:4': 'Acacia Sapling',
      'SCAVENGER_TALISMAN': 'Scavenger Talisman',
      'SEAL_OF_THE_FAMILY': 'Seal of the Family',
      'SEEDS': 'Seeds',
      'SIGN': 'Sign',
      'SILVER_FANG': 'Silver Fang',
      'SKULL_ITEM': 'Skeleton Skull',
      'SKYBLOCK_TABLE': 'Dark Oak Table',
      'SLIME_BOW': 'Slime Bow',
      'SMALL_XTREE': 'Small Holiday Tree',
      'SMOOTH_BRICK:3': 'Chiseled Stone Bricks',
      'SNOWMAN': 'Derpy Snowman',
      'SNOW_SUIT_BOOTS': 'Snow Suit Boots',
      'SOUL_SAND': 'Soul Sand',
      'SPEEDSTER_LEGGINGS': 'Speedster Leggings',
      'SPIDER_CATALYST': 'Spider Catalyst',
      'SPIDER_TALISMAN': 'Spider Talisman',
      'SPONGE_CHESTPLATE': 'Sponge Chestplate',
      'SPOOKY_BOOTS': 'Spooky Boots',
      'SPOOKY_PIE': 'Spooky Pie',
      'SPRUCE_FENCE_GATE': 'Spruce Fence Gate',
      'STAINED_CLAY': 'White Hardened Clay',
      'STAINED_CLAY:13': 'Green Hardened Clay',
      'STAINED_CLAY:5': 'Lime Hardened Clay',
      'STAINED_GLASS:11': 'Blue Stained Glass',
      'STAINED_GLASS:3': 'Light Blue Stained Glass',
      'STAINED_GLASS_PANE:10': 'Purple Stained Glass Pane',
      'STAINED_GLASS_PANE:2': 'Magenta Stained Glass Pane',
      'STAINED_GLASS_PANE:7': 'Gray Stained Glass Pane',
      'STEP:2': 'Wooden Slab',
      'STICK': 'Stick',
      'STONE:2': 'Polished Granite',
      'STONE_HOE': 'Stone Hoe',
      'STONE_SWORD': 'Stone Sword',
      'STRONG_DRAGON_BOOTS': 'Strong Dragon Boots',
      'SUGAR': 'Sugar',
      'SUPERBOOM_TNT': 'Superboom TNT',
      'SUPERIOR_FRAGMENT': 'Superior Dragon Fragment',
      'TACTICIAN_SWORD': 'Tactician\'s Sword',
      'TANK_MINER_LEGGINGS': 'Miner Leggings',
      'TARANTULA_SILK': 'Tarantula Silk',
      'THE_SHREDDER': 'Shredder',
      'TORCH': 'Torch',
      'TREECAPITATOR_AXE': 'Treecapitator',
      'UNDEAD_CATALYST': 'Undead Catalyst',
      'UNSTABLE_DRAGON_HELMET': 'Unstable Dragon Helmet',
      'VIKING_TEAR': 'Viking\'s Tear',
      'WAND_OF_HEALING': 'Wand of Healing',
      'WATER_HYDRA_HEAD': 'Water Hydra Head',
      'WEATHER_STICK': 'Weather Stick',
      'WHITE_GIFT': 'White Gift',
      'WISE_DRAGON_HELMET': 'Wise Dragon Helmet',
      'WOLF_PAW': 'Wolf Paw',
      'WOOD:1': 'Spruce Wood Plank',
      'WOOD_CHEST': 'Wood Chest+',
      'WOOD_SINGULARITY': 'Wood Singularity',
      'WOOD_STEP:2': 'Birch Wood Slab',
      'WOOD_SWORD': 'Wooden Sword',
      'WOOL:11': 'Blue Wool',
      'WOOL:2': 'Magenta Wool',
      'WOOL:7': 'Gray Wool',
      'YELLOW_FLOWER': 'Dandelion',
      'YOUNG_DRAGON_HELMET': 'Young Dragon Helmet',
      'ZOMBIE_CHESTPLATE': 'Zombie Chestplate',
      'ZOMBIE_PICKAXE': 'Zombie Pickaxe',
      'APPLE': 'Apple',
      'ARMOR_OF_MAGMA_LEGGINGS': 'Armor of Magma Leggings',
      'ASPECT_OF_THE_DRAGON': 'Aspect of the Dragons',
      'BAKED_POTATO': 'Baked Potato',
      'BAT_PERSON_BOOTS': 'Bat Person Boots',
      'BAT_TALISMAN': 'Bat Talisman',
      'BEACH_CHAIR_PLUS': 'Beach Chair+',
      'BIG_XTREE': 'Tall Holiday Tree',
      'BIRCH_WOOD_STAIRS': 'Birch Wood Stairs',
      'BLAZE_HAT': 'Blaze Hat',
      'BLESSED_BAIT': 'Blessed Bait',
      'BOOK': 'Book',
      'BOTTLE_OF_JYRRE': 'Bottle of Jyrre',
      'BREWING_PLUS': 'Brewing+',
      'BROKEN_PIGGY_BANK': 'Broken Piggy Bank',
      'CACTUS_BOOTS': 'Cactus Boots',
      'CAMPFIRE': 'Fire Pit',
      'CANDY_TALISMAN': 'Candy Talisman',
      'CARPET:12': 'Brown Carpet',
      'CARPET:5': 'Lime Carpet',
      'CARROT_ITEM': 'Carrot',
      'CHAINMAIL_CHESTPLATE': 'Chainmail Chestplate',
      'CHEAP_COFFEE': 'Cheap Coffee',
      'CHESTPLATE_OF_THE_PACK': 'Chestplate of the Pack',
      'CLAY_BRICK': 'Brick',
      'COAL_BLOCK': 'Block of Coal',
      'COBBLE_WALL:1': 'Mossy Cobblestone Wall',
      'COLD_ONES': 'Cola Cooler',
      'COOKED_FISH': 'Cooked Fish',
      'CRAFTING_PLUS': 'Crafting Table+',
      'CRYSTAL_BOOTS': 'Crystal Boots',
      'DANGER_1_PORTAL': 'Portal to Spider\'s Den',
      'DARK_OAK_FENCE': 'Dark Oak Fence',
      'DEAD_BUSH': 'Dead Bush',
      'DESERT_ISLAND': 'Desert Island',
      'DIAMOND_BARDING': 'Diamond Horse Armor',
      'DIAMOND_HELMET': 'Diamond Helmet',
      'DIAMOND_SPADE': 'Diamond Shovel',
      'DINING_TABLE': 'Dining Table',
      'DIVER_HELMET': 'Diver\'s Mask',
      'DOUBLE_PLANT:4': 'Rose Bush',
      'EFFICIENT_AXE': 'Efficient Axe',
      'EMBER_BOOTS': 'Ember Boots',
      'EMBER_ROD': 'Ember Rod',
      'EMERALD_ARMOR_LEGGINGS': 'Emerald Armor Leggings',
      'EMPTY_MAP': 'Empty Map',
      'ENCHANTED_BLAZE_ROD': 'Enchanted Blaze Rod',
      'ENCHANTED_BREAD': 'Enchanted Bread',
      'ENCHANTED_CARROT': 'Enchanted Carrot',
      'ENCHANTED_COAL': 'Enchanted Coal',
      'ENCHANTED_COOKED_MUTTON': 'Enchanted Cooked Mutton',
      'ENCHANTED_DIAMOND': 'Enchanted Diamond',
      'ENCHANTED_ENDER_PEARL': 'Enchanted Ender Pearl',
      'ENCHANTED_FIREWORK_ROCKET': 'Enchanted Firework Rocket',
      'ENCHANTED_GLOWSTONE_DUST': 'Enchanted Glowstone Dust',
      'ENCHANTED_GUNPOWDER': 'Enchanted Gunpowder',
      'ENCHANTED_ICE': 'Enchanted Ice',
      'ENCHANTED_JUNGLE_LOG': 'Enchanted Jungle Wood',
      'ENCHANTED_MAGMA_CREAM': 'Enchanted Magma Cream',
      'ENCHANTED_OAK_LOG': 'Enchanted Oak Wood',
      'ENCHANTED_POPPY': 'Enchanted Poppy',
      'ENCHANTED_PUFFERFISH': 'Enchanted Pufferfish',
      'ENCHANTED_RABBIT_FOOT': 'Enchanted Rabbit Foot',
      'ENCHANTED_RAW_SALMON': 'Enchanted Raw Salmon',
      'ENCHANTED_ROTTEN_FLESH': 'Enchanted Rotten Flesh',
      'ENCHANTED_SNOW_BLOCK': 'Enchanted Snow Block',
      'ENCHANTED_SUGAR': 'Enchanted Sugar',
      'ENCHANTING_PLUS': 'Enchanting Table+',
      'ENDER_CHEST': 'Ender Chest',
      'ENDSTONE_CHEST': 'Endstone Chest+',
      'END_LEGGINGS': 'Ender Leggings',
      'EXPLOSIVE_BOW': 'Explosive Bow',
      'FAIRY_CHESTPLATE': 'Fairy\'s Polo',
      'FANCY_TUXEDO_BOOTS': 'Fancy Tuxedo Oxfords',
      'FARMER_ROD': 'Farmer\'s Rod',
      'FARM_ARMOR_BOOTS': 'Farm Armor Boots',
      'FARM_SUIT_CHESTPLATE': 'Farm Suit Chestplate',
      'FEATHER_RING': 'Feather Ring',
      'FIREBALL': 'Fire Charge',
      'FISHING_ROD': 'Fishing Rod',
      'FISH_BAIT': 'Fish Bait',
      'FLINT_SHOVEL': 'Flint Shovel',
      'FOOD_TROUGH': 'Food Trough',
      'FORAGING_5_PORTAL': 'Portal to Dark Thicket',
      'FROZEN_BLAZE_CHESTPLATE': 'Frozen Blaze Chestplate',
      'FURNACE': 'Furnace',
      'GHAST_TEAR': 'Ghast Tear',
      'GLASS': 'Glass',
      'GOLDEN_APPLE:1': 'Enchanted Golden Apple',
      'GOLD_BARDING': 'Gold Horse Armor',
      'GOLD_CHESTPLATE': 'Golden Chestplate',
      'GOLD_LEGGINGS': 'Golden Leggings',
      'GOLD_RECORD': 'Music Disc - 13',
      'GOLEM_ARMOR_HELMET': 'Golem Armor Helmet',
      'GRAPPLING_HOOK': 'Grappling Hook',
      'GREEN_CANDY': 'Green Candy',
      'GRIZZLY_BAIT': 'Grizzly Bait',
      'GUARDIAN_CHESTPLATE': 'Guardian Chestplate',
      'HARDENED_DIAMOND_HELMET': 'Hardened Diamond Helmet',
      'HASTE_BLOCK': 'Haste Block',
      'HEALING_TALISMAN': 'Healing Talisman',
      'HORSEMAN_CANDLE': 'Horseman\'s Candle',
      'HUNTER_KNIFE': 'Hunter Knife',
      'ICE': 'Ice',
      'ICE_ROD': 'Ice Rod',
      'INK_SACK:11': 'Dandelion Yellow',
      'INK_SACK:2': 'Cactus Green',
      'INK_SACK:7': 'Light Gray Dye',
      'INTIMIDATION_RING': 'Intimidation Ring',
      'IRON_BOOTS': 'Iron Boots',
      'IRON_HELMET': 'Iron Helmet',
      'IRON_PICKAXE': 'Iron Pickaxe',
      'ITEM_FRAME': 'Item Frame',
      'JUNGLE_BIOME_STICK': 'Jungle Biome Stick',
      'KILLER_PERSONALITY': 'Killer Minion Skin',
      'LAPIS_ARMOR_CHESTPLATE': 'Lapis Armor Chestplate',
      'LAPIS_ORE': 'Lapis Lazuli Ore',
      'LAVA_BUCKET': 'Lava Bucket',
      'LEAFLET_LEGGINGS': 'Leaflet Pants',
      'LEATHER_LEGGINGS': 'Leather Leggings',
      'LEAVES_2': 'Acacia Leaves',
      'LEVER': 'Lever',
      'LOG:2': 'Birch Wood',
      'MAGMA_BOW': 'Magma Bow',
      'MAP': 'Map',
      'MASTIFF_CHESTPLATE': 'Mastiff Chestplate',
      'MELON': 'Melon',
      'MILK_BUCKET': 'Milk Bucket',
      'MINER_OUTFIT_LEGGINGS': 'Miner\'s Outfit Leggings',
      'MINION_EXPANDER': 'Minion Expander',
      'MUSHROOM_BOOTS': 'Mushroom Boots',
      'MUSIC_PANTS': 'Stereo Pants',
      'NETHER_BIOME_STICK': 'Nether Biome Stick',
      'NETHER_STALK': 'Nether Wart',
      'NIGHT_VISION_CHARM': 'Night Vision Charm',
      'OLD_DRAGON_HELMET': 'Old Dragon Helmet',
      'OVERFLUX_POWER_ORB': 'Overflux Power Orb',
      'PERFECT_BOOTS_1': 'Perfect Boots - Tier I',
      'PERFECT_BOOTS_3': 'Perfect Boots - Tier III',
      'PERFECT_CHESTPLATE_12': 'Perfect Chestplate - Tier XII',
      'PERFECT_CHESTPLATE_6': 'Perfect Chestplate - Tier VI',
      'PERFECT_HELMET_5': 'Perfect Helmet - Tier V',
      'PERFECT_LEGGINGS_1': 'Perfect Leggings - Tier I',
      'PERFECT_LEGGINGS_3': 'Perfect Leggings - Tier III',
      'PIGGY_BANK': 'Piggy Bank',
      'PLUMBER_SPONGE': 'Plumber\'s Sponge',
      'PORK': 'Raw Porkchop',
      'POWERED_RAIL': 'Powered Rail',
      'PRISMARINE_SHARD': 'Prismarine Shard',
      'PROTECTOR_DRAGON_CHESTPLATE': 'Protector Dragon Chestplate',
      'PULPOUS_ORANGE_JUICE': 'Pulpous Orange Juice',
      'PUMPKIN_LEGGINGS': 'Pumpkin Leggings',
      'QUARTZ_BLOCK': 'Block of Quartz',
      'QUARTZ_ORE': 'Nether Quartz Ore',
      'RABBIT_HIDE': 'Rabbit Hide',
      'RAW_CHICKEN': 'Raw Chicken',
      'REAPER_MASK': 'Reaper Mask',
      'RECORD_11': 'Music Disc - 11',
      'RECORD_6': 'Music Disc - Mall',
      'REDSTONE_BLOCK': 'Block of Redstone',
      'REDSTONE_TORCH_ON': 'Redstone Torch',
      'RED_GIFT': 'Red Gift',
      'RED_ROSE:2': 'Allium',
      'RED_ROSE:7': 'Pink Tulip',
      'RED_SANDSTONE:2': 'Red Smooth Sandstone',
      'REVENANT_CHESTPLATE': 'Revenant Chestplate',
      'REVIVED_HEART': 'Revived Heart',
      'ROOKIE_AXE': 'Rookie Axe',
      'RUNE': '◆ Hearts Rune I',
      'SANDSTONE:1': 'Chiseled Sandstone',
      'SAPLING': 'Oak Sapling',
      'SAPLING:5': 'Dark Oak Sapling',
      'SCORPION_BOW': 'Scorpion Bow',
      'SEA_CREATURE_ARTIFACT': 'Sea Creature Artifact',
      'SHADY_RING': 'Shady Ring',
      'SILENCE_BLOCK': 'Silence Block',
      'SKELETON_HAT': 'Skeleton Hat',
      'SLAYER_ENERGY_DRINK': 'Slayer�� Energy Drink',
      'SLIME_HAT': 'Slime Hat',
      'SMOOTH_BRICK': 'Stone Bricks',
      'SNOW_BALL': 'Snowball',
      'SNOW_SUIT_CHESTPLATE': 'Snow Suit Chestplate',
      'SPECKLED_MELON': 'Glistering Melon',
      'SPEEDSTER_ROD': 'Speedster Rod',
      'SPIDER_EYE': 'Spider Eye',
      'SPIKED_BAIT': 'Spiked Bait',
      'SPONGE_HELMET': 'Sponge Helmet',
      'SPOOKY_CHESTPLATE': 'Spooky Chestplate',
      'SPOOKY_SHARD': 'Spooky Shard',
      'SPRUCE_WOOD_STAIRS': 'Spruce Wood Stairs',
      'STAINED_CLAY:1': 'Orange Hardened Clay',
      'STAINED_CLAY:14': 'Red Hardened Clay',
      'STAINED_CLAY:7': 'Gray Hardened Clay',
      'STAINED_GLASS:13': 'Green Stained Glass',
      'STAINED_GLASS:4': 'Yellow Stained Glass',
      'STAINED_GLASS_PANE:11': 'Blue Stained Glass Pane',
      'STAINED_GLASS_PANE:3': 'Light Blue Stained Glass Pane',
      'STAINED_GLASS_PANE:8': 'Light Gray Stained Glass Pane',
      'STEP:3': 'Cobblestone Slab',
      'STOCKING': 'Stocking',
      'STONE:3': 'Diorite',
      'STONE_PICKAXE': 'Stone Pickaxe',
      'STONK_PICKAXE': 'Stonk',
      'STRONG_DRAGON_CHESTPLATE': 'Strong Dragon Chestplate',
      'SUGAR_CANE': 'Sugar Cane',
      'SUPERIOR_DRAGON_BOOTS': 'Superior Dragon Boots',
      'SUPER_COMPACTOR_3000': 'Super Compactor 3000',
      'TAIGA_BIOME_STICK': 'Taiga Biome Stick',
      'TARANTULA_BOOTS': 'Tarantula Boots',
      'TARANTULA_TALISMAN': 'Tarantula Talisman',
      'THIN_GLASS': 'Glass Pane',
      'TOXIC_ARROW_POISON': 'Toxic Arrow Poison',
      'TRICK_OR_TREAT_BAG': 'Trick or Treat Bag',
      'UNDEAD_PERSONALITY': 'Undead Minion Skin',
      'UNSTABLE_DRAGON_LEGGINGS': 'Unstable Dragon Leggings',
      'VILLAGE_TALISMAN': 'Village Affinity Talisman',
      'WAND_OF_MENDING': 'Wand of Mending',
      'WATER_LILY': 'Lily Pad',
      'WEB': 'Web',
      'WINTER_DISC': 'Winter Disc',
      'WISE_DRAGON_LEGGINGS': 'Wise Dragon Leggings',
      'WOLF_RING': 'Wolf Ring',
      'WOOD:2': 'Birch Wood Plank',
      'WOOD_DOOR': 'Oak Door',
      'WOOD_SPADE': 'Wooden Shovel',
      'WOOD_STEP:3': 'Jungle Wood Slab',
      'WOOD_TALISMAN': 'Wood Affinity Talisman',
      'WOOL:12': 'Brown Wool',
      'WOOL:3': 'Light Blue Wool',
      'WOOL:8': 'Light Gray Wool',
      'YETI_ROD': 'Yeti Rod',
      'YOUNG_DRAGON_LEGGINGS': 'Young Dragon Leggings',
      'ZOMBIE_GRAVE': 'Zombie Grave',
      'ZOMBIE_RING': 'Zombie Ring',
      'STRONG_DRAGON_HELMET': 'Strong Dragon Helmet',
      'SULPHUR': 'Gunpowder',
      'SUPERIOR_DRAGON_CHESTPLATE': 'Superior Dragon Chestplate',
      'SUPER_EGG': 'Super Enchanted Egg',
      'TANK_MINER_BOOTS': 'Miner Boots',
      'TARANTULA_CHESTPLATE': 'Tarantula Chestplate',
      'TARANTULA_WEB': 'Tarantula Web',
      'TIKI_TORCH': 'Tiki Torch',
      'TRAINING_DUMMY': 'Training Dummy',
      'TRIPWIRE_HOOK': 'Tripwire Hook',
      'UNDEAD_SWORD': 'Undead Sword',
      'UNSTABLE_FRAGMENT': 'Unstable Dragon Fragment',
      'VINE': 'Vines',
      'WAND_OF_RESTORATION': 'Wand of Restoration',
      'WATER_TROUGH': 'Water Trough',
      'WEIRD_TUBA': 'Weird Tuba',
      'WINTER_ROD': 'Winter Rod',
      'WISE_FRAGMENT': 'Wise Dragon Fragment',
      'WOLF_TALISMAN': 'Wolf Talisman',
      'WOOD:3': 'Jungle Wood Plank',
      'WOOD_HOE': 'Wooden Hoe',
      'WOOD_STAIRS': 'Oak Wood Stairs',
      'WOOD_STEP:4': 'Acacia Wood Slab',
      'WOOL': 'White Wool',
      'WOOL:13': 'Green Wool',
      'WOOL:4': 'Yellow Wool',
      'WOOL:9': 'Cyan Wool',
      'YOUNG_FRAGMENT': 'Young Dragon Fragment',
      'ZOMBIE_HAT': 'Zombie Hat',
      'ZOMBIE_SWORD': 'Zombie Sword',
      'WRITTEN_BOOK': 'Written Book',
      'LOG_2:0': 'Acacia Wood',
      'PERFECT_HELMET_10': 'Perfect Helmet - Tier X',
      'SPONGE:1': 'Wet Sponge',
      'STAINED_GLASS:6': 'Pink Stained Glass',
      'PERFECT_HELMET_7': 'Perfect Helmet - Tier VII',
      'CARPET:6': 'Pink Carpet',
      'CHICK_NEST': 'Chick Nest',
      'BUNNY_JERRY': 'Bunny Jerry',
      'BUNNY': 'Bunny',
      'EGG_PILE': 'Egg Pile',
      'EASTER_BASKET': 'Easter Basket',
      'LADY_BUG_PERSONALITY': 'Lady Bug Minion Skin',
      'BEE_PERSONALITY': 'Bee Minion Skin',
      'BUNNY_PERSONALITY': 'Bunny Minion Skin',
      'CARPET:10': 'Purple Carpet',
      'CARPET:13': 'Green Carpet',
      'CARPET:4': 'Yellow Carpet',
      'PERFECT_LEGGINGS_8': 'Perfect Leggings - Tier VIII',
      'PERFECT_LEGGINGS_7': 'Perfect Leggings - Tier VII',
      'PERFECT_BOOTS_9': 'Perfect Boots - Tier IX',
      'RED_SANDSTONE_STAIRS': 'Red Sandstone Stairs',
      'PERFECT_HELMET_11': 'Perfect Helmet - Tier XI',
      'WHEAT_ISLAND_CRYSTAL': 'Wheat Crystal'
    }
  }
}
